### DISCUSSION TITLE
pipenv.exceptions.ResolutionFailure message is misleading/incomplete?

### DISCUSSION THREAD

**Discussion by evilensky** [pypa/pipenv#5558] [General]
Hi!  Is it correct that when there is trouble authenticating to a third party index, the error message blames dependency resolution problems and provides an unhelpful hint?

I have a pipfile that starts like so:

```toml
[[source]]
url = "https://${USER}:${PASSWORD}@privateindex.example.com/index/api/pypi/pypi/simple"
verify_ssl = true
name = "pypi"

[requires]
python_version = "3.9"
```

I find that if either variable is not set correctly, results in this error message:

```
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
```

Which is sort of technically correct, but yet very much incomplete / without context.

Is this a deliberate design choice? Is there an exception being caught somewhere underneath this message that it would be more useful to present directly to the user so they can diagnose the issue?

I find myself well-trained at this point to check my indices' configurations at first sight of this, but it seems unhelpful to new users.
