### ISSUE TITLE
UnsupportedPythonVersion with two Pipfile [[source]] blocks

### ISSUE THREAD

**Issue by commandtab** [pypa/pipenv#1179]
When installing `python-swiftclient` from a Pipfile with a single `[[source]]` block, like so:

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
python-swiftclient = {version="==3.4.0", index="pypi"}
```

`python-swiftclient` installs successfully. So far so good. But, when my Pipfile has two valid `[[source]]` blocks...

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://pypi.companyname.com"
verify_ssl = true
name = "privatepypi"

[packages]
python-swiftclient = {version="==3.4.0", index="pypi"}
```

Installation of `python-swiftclient` errors with...

```
pip.exceptions.UnsupportedPythonVersion: futures requires
Python '>=2.6, <3' but the running Python is 3.6.3
```

...despite explicitly specifying which index `python-swiftclient` should be installed from (`index="pypi"`). Why does having a second (and theoretically unused) `[[source]]` block affect installation of that package? (Of note, `privatepypi` does not contain a fork of `python-swiftclient`.)

##### Describe your environment

1. OS Type: macOS Sierra 10.12.6
1. Python version: 3.6.3
1. Pipenv version: 8.3.2

##### Expected result

I expected `python-swiftclient` to install from public pypi without issue when two `[[source]]` blocks are present and the correct index to use is specified for the given package.

##### Actual result

`python-swiftclient` fails to install when two `[[source]]` blocks are present, suggesting that the un-referenced `[[source]]` is being consulted or is affecting dependency resolution somehow.

##### Steps to replicate

Write this to a `Pipfile`:

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://pypi.companyname.com"
verify_ssl = true
name = "privatepypi"

[packages]
python-swiftclient = {version="==3.4.0", index="pypi"}
```

Then do `pipenv --three install` to observe the error:

```
pip.exceptions.UnsupportedPythonVersion: futures 
requires Python '>=2.6, <3' but the running Python is 3.6.3
```

Any suggestions? Thanks!
