### ISSUE TITLE
jupyter+pipenv+tmux+tmuxp is very powerful

### ISSUE THREAD

**Issue by wlccgp3** [pypa/pipenv#1281]
> I just want share my experiences.

~/.tmuxp/dtston.yml
```
start_directory: ~/
before_script: ./pre_session.sh
session_name: dtston
windows:
- window_name: jupyter
  start_directory: $HOME/Documents/机器学习
  layout: main-vertical
  panes:
    - shell_command:
      - source `pipenv --venv`/bin/activate  # if use pipenv shell, next cmd will be not work
      - ipython3 kernel install --user --name python_ml --display-name 机器学习  # don't worry it won't repeat creat
      - jupyter notebook
    - shell_command:
      - source `pipenv --venv`/bin/activate
```

~/.tmuxp/pre_session.sh
```
#!/bin/sh
service elasticsearch status | grep 'running'
if [ $? -eq 0 ]; then :
else service elasticsearch start
fi
```

~/.jupyter/jupyter_notebook_config.py
```
import os
import sys

cur_dir = os.getcwd()
# print(cur_dir)
python_path = os.environ.get('PYTHONPATH', '')
if cur_dir not in python_path:
    if python_path:
        python_path = python_path + ':' + cur_dir
    else:
        python_path = cur_dir
os.environ['PYTHONPATH'] = python_path

```
