### ISSUE TITLE
Setting PIP_INDEX_URL results in two [[source]] sections

### ISSUE THREAD

**Issue by hynek** [pypa/pipenv#1311]
##### Describe your environment

1. OS Type macOS
1. Python version: `$ python -V` 3.6.4
1. Pipenv version: `$ pipenv --version` 9.1.0 (aka master)

##### Expected result

Setting PIP_INDEX_URL creates a Pipfile with a [[source]] set to the contents.

##### Actual result

Pipfile contains both the default section pointing to "https://pypi.python.org/pypi" and a section with my settings.

##### Steps to replicate

Since I don’t know a public PyPI index, let’s do a simpler thing:

`env PIP_INDEX_URL=https://pypi.python.org/pypi pipenv install requests`

results in

```toml
[[source]]

url = "https://pypi.python.org/pypi"
verify_ssl = true
name = "pypi"


[[source]]

url = "https://pypi.python.org/pypi"
verify_ssl = true
name = "pypi"
```

If they were different, the correct one would be at the first place.
