### ISSUE TITLE
Installing packges from requirements.txt complains about require-hashes and some packages not having their versions pinned

### ISSUE THREAD

**Issue by c-garcia** [pypa/pipenv#1449]
`pip install -r requirements.txt` using the file generated by `pipenv lock -r` complains about some packages not having their version pinned with `==`. Among them, `setuptools` and `six`.

It may be related to #1417

##### Describe your environment

1. OS Type: MacOS 10.12.6 (with MacPorts)
1. Python version: `3.6.4`
1. Pipenv version: `9.1.0` (installed from master, on Feb, 18th)

##### Expected result

I expected the all packages being installed in the `target` directory with versions coherent with `Pipfile.lock`

##### Actual result

```
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    setuptools>=0.6b1 from https://pypi.python.org/packages/43/41/033a273f9a25cb63050a390ee8397acbc7eae2159195d85f06f17e7be45a/setuptools-38.5.1-py2.py3-none-any.whl#md5=908b8b5e50bf429e520b2b5fa1b350e5 (from injector==0.13.4->-r target/requirements.txt (line 5))
    six from https://pypi.python.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl#md5=866ab722be6bdfed6830f3179af65468 (from purl==1.3.1->-r target/requirements.txt (line 6))
```

##### Steps to replicate

With this Pipfile

```toml
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

purl = "*"
requests = "*"
python-dotenv = "*"
injector = "*"
voluptuous = "*"


[dev-packages]

"boto3" = "*"
pytest = "*"
pytest-mock = "*"
selenium = "*"
bpython = "*"
```

Commands

```sh
mkdir target
pipenv lock -r > target/requirements.txt
# with pip executed from a shell created with pipenv shell or from a new one
pip install -r target/requirements.txt -t target
```
