### ISSUE TITLE
futures==3.2.0

### ISSUE THREAD

**Issue by kennethreitz** [pypa/pipenv#1586]
```
CRITICAL:pip.index:Could not find a version that satisfies the requirement futures==3.2.0 (from versions: 0.2.python3, 0.1, 0.2, 1.0, 2.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1)
```

**Comment by vphilippon** [comment]
Quick guess:
From https://pypi.python.org/pypi/futures:
> Requires Python: >=2.6, <3

You might somehow have a corrupted dependency cache that believes (due to previous resolver bug) that `futures==3.2.0` is still a dependency under Py3. I'd clear that just in case before digging deeper.

**Comment by kennethreitz** [comment]
can no longer reproduce

**Comment by kennethreitz** [comment]
i lied

**Comment by kennethreitz** [comment]
```toml
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]

futures = "*"

[dev-packages]

[requires]

python_version = "3.6"
```

leads to

```json
{
    "_meta": {
        "hash": {
            "sha256": "defaf2233df08ddd288f75787d4a8904217ecf22fba389a152b64f50144c6ce6"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "futures": {
            "hashes": [
                "sha256:51ecb45f0add83c806c68e4b06106f90db260585b25ef2abfcda0bd95c0132fd",
                "sha256:c4884a65654a7c45435063e14ae85280eb1f111d94e542396717ba9828c4337f"
            ],
            "version": "==3.1.1"
        }
    },
    "develop": {}
}
```

**Comment by kennethreitz** [comment]
This file:

```toml
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]

futures = {version = "==3.2", python_version = "<'3.0.0'"}
```

Leads to:

```
Locking [dev-packages] dependencies…
Locking [packages] dependencies…

CRITICAL:pip.index:Could not find a version that satisfies the requirement futures==3.2 (from versions: 0.2.python3, 0.1, 0.2, 1.0, 2.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1)
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
No matching distribution found for futures==3.2
```
