### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by SalchiPapa** [pypa/pipenv#1625]
During a vagrant provisioning, pipenv recently started to fail at creating the Pipfile, Pipfile.lock files and install the packages.

Requirements.txt:

```
MySQL-python
Pillow
closure
mock
yuicompressor
zc.buildout
requests
webtest
webob
django-webtest
django-jenkins
coverage
pep8
pyflakes
freezegun
fabric
Sphinx
pyparsing
django
```

**This was working until yesterday.**

##### Describe your environment

1. OS Type: Ubuntu Xenial 64 bits
2. Python version: 2.7.12
3. Pipenv version: 11.1.5
4. VirtualBox: 5.2.8 r121009
5. Vagrant: 2.0.1

##### Expected result

This should create Pipfile, Pipfile.lock and install the packages.

##### Actual result

```
    default: requirements.txt found, instead of Pipfile! Converting…
    default: Traceback (most recent call last):
    default:   File "/usr/local/bin/pipenv", line 9, in <module>
    default:     
    default: load_entry_point('pipenv==11.1.5', 'console_scripts', 'pipenv')()
    default:   File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    default:     
    default: return self.main(*args, **kwargs)
    default:   File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    default:     
    default: rv = self.invoke(ctx)
    default:   File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    default:     
    default: return _process_result(sub_ctx.command.invoke(sub_ctx))
    default:   File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    default:     
    default: return ctx.invoke(self.callback, **ctx.params)
    default:   File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    default:     
    default: return callback(*args, **kwargs)
    default:   File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 197, in install
    default:     
    default: selective_upgrade=selective_upgrade
    default:   File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 1731, in do_install
    default:     
    default: ensure_project(three=three, python=python, system=system, warn=True, deploy=deploy, skip_requirements=skip_requirements)
    default:   File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 652, in ensure_project
    default:     ensure_pipfile(validate=validate, skip_requirements=skip_requirements)
    default:   File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 319, in ensure_pipfile                                           
    default:     project.create_pipfile(python=python)                                                                                             
    default:   File "/usr/local/lib/python2.7/dist-packages/pipenv/project.py", line 439, in create_pipfile
    default:     data[u'requires'] = {'python_version': python_version(self.which('python'))[:len('2.7')]}
    default: TypeError:                                                                                                                            
    default: 'NoneType' object has no attribute '__getitem__'
    default: /usr/local/lib/python2.7/dist-packages/pipenv/utils.py:1149: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-hmGOVq-requirements'>                                                                                                                              
    default:   warnings.warn(warn_message, ResourceWarning)
```

##### Steps to replicate

```bash
# This script is called when `vagrant up` or `vagrant provision` are called.
function install_python_dependencies {
    pip install pipenv  >> bootstrap.log
    cd /vagrant
   # don't use virtual env in vagrant/docker
    pipenv install --system  >> bootstrap.log
}
install_python_dependencies
```

Related: #90, #132 

* **'NoneType' object has no attribute `'__getitem__'`**
