### ISSUE TITLE
Pipenv duplicates 2nd-level dependencies and "file" dependencies

### ISSUE THREAD

**Issue by jleclanche** [pypa/pipenv#1786]
```toml
# Pipfile
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
dj-paypal = "0.7.0"
"1793fa7" = {file = "https://github.com/jleclanche/dj-stripe/archive/master.tar.gz"}
```

This pipfile depends on two packages:
* dj-stripe, pulled from git master tarball (`https://github.com/jleclanche/dj-stripe/archive/master.tar.gz`)
* dj-paypal, which itself depends on dj-stripe

The resulting environment is corrupt however: dj-stripe will be installed twice, in mismatching ways.

pipenv should either resolve the file dependency first and understand that it is dj-stripe and satisfies the dj-paypal "dj-stripe" dependency, or at least warn/error rather than create a corrupt env.

Edit: dj-paypal 0.7.1 drops the dj-stripe dependency, so I've locked it at 0.7.0
