### ISSUE TITLE
Could not find a version that matches sqlalchemy==1.2.0b3,>=0.7.6,>=0.8.0

### ISSUE THREAD

**Issue by frostming** [pypa/pipenv#1788]
Be sure to check the existing issues (both open and closed!).

Describe the issue briefly here.

Please run `$ python -m pipenv.help`, and paste the results here.

If you're on MacOS, just run the following:

    $ python -m pipenv.help | pbcopy

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.8.3'`

Pipenv location: `'/usr/local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/local/opt/python/bin/python3.6'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/usr/local/bin/python3.6`

  - `2.7.10`: `/usr/bin/python`
  - `3.6.4`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.4.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST '
                     '2017; root:xnu-4570.41.2~1/RELEASE_X86_64',
 'python_full_version': '3.6.4',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `TERM_PROGRAM`
  - `TERM`
  - `SHELL`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `ZSH`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `PAGER`
  - `LSCOLORS`
  - `PWD`
  - `LANG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `LC_CTYPE`
  - `GOPATH`
  - `PROMPT_EOL_MARK`
  - `DISPLAY`
  - `COLORTERM`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`
  - `PIPENV_ACTIVE`
  - `OLDPWD`
  - `PS1`
  - `COS_SECRET_ID`
  - `FLASK_DEBUG`
  - `FLASK_APP`
  - `COS_SECRET_KEY`
  - `DIRENV_DIR`
  - `DIRENV_WATCHES`
  - `DIRENV_DIFF`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/Users/fming/wkspace/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/aria2/bin:/opt/X11/bin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `zh_CN.UTF-8`
  - `PWD`: `/Users/fming/wkspace/github/flaskblog`

---------------------------

Contents of `Pipfile` ('/Users/fming/wkspace/github/flaskblog/Pipfile'):

```toml
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

mistune-contrib = {git = "https://github.com/frostming/mistune-contrib.git", editable = true, ref = "36c5ff9d2c8308bd03bf28fe28cc0755a6a86864"}
alembic = "==0.9.8"
babel = "==2.5.3"
click = "==6.7"
flask-admin = "==1.5.0"
flask-babel = "==0.11.2"
flask-blogtheme = "==0.2.2"
flask-login = "==0.4.0"
flask-migrate = "==2.1.1"
flask-moment = "==0.5.1"
flask-sqlalchemy = "==2.2"
flask-sslify = "==0.1.5"
flask = "==0.12.2"
gunicorn = "==19.7.1"
itsdangerous = "==0.24"
"jinja2" = "==2.10"
mako = "==1.0.7"
markupsafe = "==1.0"
mistune = "==0.7.4"
"psycopg2" = "==2.7.4"
python-dateutil = "==2.7.0"
python-editor = "==1.0.3"
python-slugify = "==1.2.4"
pytz = "==2018.3"
pyyaml = "==3.12"
six = "==1.11.0"
unidecode = "==1.0.22"
werkzeug = "==0.14.1"
wtforms = "==2.1"
sqlalchemy = "==1.2.0b3"


[dev-packages]



[requires]

python_version = "3.6"

```

</details>

------------

##### Expected result

Write the hash of SQLAlchemy==1.2.0b3 into `Pipfile.lock`

##### Actual result

All deps can be installed correctly with `--skip-lock` but throws error when `pipenv lock`:

> Could not find a version that matches sqlalchemy==1.2.0b3,>=0.7.6,>=0.8.0

<details><summary>`pipenv graph` result</summary>

```
Flask-Admin==1.5.0
  - Flask [required: >=0.7, installed: 0.12.2]
    - click [required: >=2.0, installed: 6.7]
    - itsdangerous [required: >=0.21, installed: 0.24]
    - Jinja2 [required: >=2.4, installed: 2.10]
      - MarkupSafe [required: >=0.23, installed: 1.0]
    - Werkzeug [required: >=0.7, installed: 0.14.1]
  - wtforms [required: Any, installed: 2.1]
Flask-Babel==0.11.2
  - Babel [required: >=2.3, installed: 2.5.3]
    - pytz [required: >=0a, installed: 2018.3]
  - Flask [required: Any, installed: 0.12.2]
    - click [required: >=2.0, installed: 6.7]
    - itsdangerous [required: >=0.21, installed: 0.24]
    - Jinja2 [required: >=2.4, installed: 2.10]
      - MarkupSafe [required: >=0.23, installed: 1.0]
    - Werkzeug [required: >=0.7, installed: 0.14.1]
  - Jinja2 [required: >=2.5, installed: 2.10]
    - MarkupSafe [required: >=0.23, installed: 1.0]
Flask-BlogTheme==0.2.2
  - pyyaml [required: Any, installed: 3.12]
Flask-Login==0.4.0
  - Flask [required: Any, installed: 0.12.2]
    - click [required: >=2.0, installed: 6.7]
    - itsdangerous [required: >=0.21, installed: 0.24]
    - Jinja2 [required: >=2.4, installed: 2.10]
      - MarkupSafe [required: >=0.23, installed: 1.0]
    - Werkzeug [required: >=0.7, installed: 0.14.1]
Flask-Migrate==2.1.1
  - alembic [required: >=0.6, installed: 0.9.8]
    - Mako [required: Any, installed: 1.0.7]
      - MarkupSafe [required: >=0.9.2, installed: 1.0]
    - python-dateutil [required: Any, installed: 2.7.0]
      - six [required: >=1.5, installed: 1.11.0]
    - python-editor [required: >=0.3, installed: 1.0.3]
    - SQLAlchemy [required: >=0.7.6, installed: 1.2.0b3]
  - Flask [required: >=0.9, installed: 0.12.2]
    - click [required: >=2.0, installed: 6.7]
    - itsdangerous [required: >=0.21, installed: 0.24]
    - Jinja2 [required: >=2.4, installed: 2.10]
      - MarkupSafe [required: >=0.23, installed: 1.0]
    - Werkzeug [required: >=0.7, installed: 0.14.1]
  - Flask-SQLAlchemy [required: >=1.0, installed: 2.2]
    - Flask [required: >=0.10, installed: 0.12.2]
      - click [required: >=2.0, installed: 6.7]
      - itsdangerous [required: >=0.21, installed: 0.24]
      - Jinja2 [required: >=2.4, installed: 2.10]
        - MarkupSafe [required: >=0.23, installed: 1.0]
      - Werkzeug [required: >=0.7, installed: 0.14.1]
    - SQLAlchemy [required: >=0.8.0, installed: 1.2.0b3]
Flask-Moment==0.5.1
  - Flask [required: Any, installed: 0.12.2]
    - click [required: >=2.0, installed: 6.7]
    - itsdangerous [required: >=0.21, installed: 0.24]
    - Jinja2 [required: >=2.4, installed: 2.10]
      - MarkupSafe [required: >=0.23, installed: 1.0]
    - Werkzeug [required: >=0.7, installed: 0.14.1]
Flask-SSLify==0.1.5
  - Flask [required: Any, installed: 0.12.2]
    - click [required: >=2.0, installed: 6.7]
    - itsdangerous [required: >=0.21, installed: 0.24]
    - Jinja2 [required: >=2.4, installed: 2.10]
      - MarkupSafe [required: >=0.23, installed: 1.0]
    - Werkzeug [required: >=0.7, installed: 0.14.1]
gunicorn==19.7.1
mistune==0.7.4
mistune-contrib==0.1
psycopg2==2.7.4
python-slugify==1.2.4
  - Unidecode [required: >=0.04.16, installed: 1.0.22]
```
</details>

##### Steps to replicate

* `pipenv install` or `pipenv lock`
