### ISSUE TITLE
Whats the correct way to install from a git repo?

### ISSUE THREAD

**Issue by kakulukia** [pypa/pipenv#1942]
I couldnt find a close match in the docs :(

-----

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.9.0'`

Pipenv location: `'/Users/andy/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv'`

Python location: `'/Users/andy/.pyenv/versions/3.6.4/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/Users/andy/.pyenv/shims/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.4`: `/Users/andy/.pyenv/shims/python3.4`
  - `3.6`: `/Users/andy/.pyenv/versions/3.6.4/bin/python3.6m`
  - `3.6`: `/Users/andy/.pyenv/versions/3.6.4/bin/python3.6`
  - `3.6`: `/Users/andy/.pyenv/shims/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`

  - `3.6.4`: `/Users/andy/.pyenv/versions/3.6.4/bin/python`
  - `3.6.4`: `/Users/andy/.pyenv/shims/python`
  - `3.6.4`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `3.6.4`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `None`: `/Users/andy/.pyenv/shims/python2`
  - `3.6.4`: `/Users/andy/.pyenv/versions/3.6.4/bin/python3`
  - `3.6.4`: `/Users/andy/.pyenv/shims/python3`
  - `3.6.4`: `/usr/local/bin/python3`
  - `3.6.4`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST '
                     '2018; root:xnu-4570.51.1~1/RELEASE_X86_64',
 'python_full_version': '3.6.4',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `CD_VIRTUAL_ENV`
  - `VIRTUALENVWRAPPER_SCRIPT`
  - `VIRTUALENVWRAPPER_PROJECT_FILENAME`
  - `TERM_PROGRAM`
  - `PYENV_ROOT`
  - `TERM`
  - `SHELL`
  - `PIPENV_VENV_IN_PROJECT`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `PYENV_VERSION`
  - `ZSH`
  - `USER`
  - `COMMAND_MODE`
  - `SSH_AUTH_SOCK`
  - `PYENV_DIR`
  - `__CF_USER_TEXT_ENCODING`
  - `VIRTUAL_ENV_DISABLE_PROMPT`
  - `PAGER`
  - `WORKON_HOME`
  - `LSCOLORS`
  - `PATH`
  - `VIRTUALENVWRAPPER_HOOK_DIR`
  - `PWD`
  - `JAVA_HOME`
  - `DJANGO_SETTINGS_MODULE`
  - `EDITOR`
  - `LANG`
  - `ITERM_PROFILE`
  - `PYENV_HOOK_PATH`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `PYENV_SHELL`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `LC_CTYPE`
  - `VIRTUALENVWRAPPER_WORKON_CD`
  - `REPORTTIME`
  - `SECURITYSESSIONID`
  - `COLORTERM`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `1`

Debug–specific environment variables:

  - `PATH`: `/Users/andy/.pyenv/versions/3.6.4/bin:/usr/local/Cellar/pyenv/1.2.2/libexec:/Users/andy/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/usr/local/sbin:.:/bin:/Users/andy/bin`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `vim`
  - `LANG`: `de_DE.UTF-8`
  - `PWD`: `/Users/andy/projects/vfk/Research-Server/portal`

---------------------------

Contents of `Pipfile` ('/Users/andy/projects/vfk/Research-Server/portal/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[packages]
django = ">=2"
wagtail = "==2.0.1"
raven = "*"
django-post-office = "*"
uwsgi = "*"
uwsgidecorators = "*"
dj-static = "*"
django-secrets = "*"
pypugjs = "*"
easy-thumbnails = "*"
django-rosetta = "*"
wagalytics = "*"
"django-gravatar2" = "*"
"django-select2" = "*"
wagtail-modeltranslation = "==0.8.1"
django-compressor = "*"
django-crispy-forms = "*"
"django-bootstrap3" = "*"
django-extensions = "*"
django-undeletable = "*"
django-redis = "*"
"fabric3" = "*"
django-libsass = "*"
"flake8" = "*"
"psycopg2-binary" = "*"
djangorestframework = "*"

["dev-packages"]
django-debug-toolbar = "*"pipenv clean
django-livereload-server = "*"
ipdb = "*"

```

</details>

----

--code might be what im looking for but if its meant to also be given a github url, its broken

toml.TomlDecodeError: Stuff after closed string. WTF?

But since the docs only mention code, it might as well just work with  local code .. the docs are kinda vague. :(

i was trying those commands .. all failed
pipenv install -c https://github.com/deschler/django-modeltranslation.git#egg=master
pipenv install "-c https://github.com/deschler/django-modeltranslation.git#egg=master"
pipenv install -e https://github.com/deschler/django-modeltranslation.git#egg=master
pipenv install "-e https://github.com/deschler/django-modeltranslation.git#egg=master"
pipenv install https://github.com/deschler/django-modeltranslation
pipenv install -c https://github.com/deschler/django-modeltranslation
pipenv install -e https://github.com/deschler/django-modeltranslation
