### ISSUE TITLE
pipenv install stuck in a mkdir/stat loop

### ISSUE THREAD

**Issue by gordol** [pypa/pipenv#2360]
Not sure how it got into this state, but ultimately, I had to just blow out the ~/.caches dir and then it went fine w/o a hitch.

Basically though, it was just stuck in a loop trying to make a directory or something...

```
root@dev0:~# ps aux | grep pipenv
fieldag+  8038  0.2  0.2 1183836 43236 pts/1   Sl+  01:57   0:00 /srv/fieldagent/.virtualenvs/fieldagent/bin/python2 /srv/fieldagent/.virtualenvs/fieldagent/bin/pipenv install --deploy
fieldag+  8048  0.2  0.2 105148 43388 pts/1    S+   01:57   0:00 /srv/fieldagent/.virtualenvs/fieldagent/bin/python2 /srv/fieldagent/.virtualenvs/fieldagent/bin/pip install --no-deps -r /tmp/pipenv-OpfNtb-requirements/pipenv-0Y6aSs-requirement.txt --require-hashes -i https://pypi.python.org/simple --exists-action w
root      8904  0.0  0.0  12784   988 pts/0    S+   02:04   0:00 grep pipenv


root@dev0:~# strace -p 8038
strace: Process 8038 attached
wait4(8048, ^Cstrace: Process 8038 detached
 <detached ...>


root@dev0:~# strace -p 8048
strace: Process 8048 attached
select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=98170}) = 0 (Timeout)
mkdir("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock", 0777) = -1 EEXIST (File exists)
stat("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock/dev0.-835f47008048", 0x7ffe07515b80) = -1 ENOENT (No such file or directory)
select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=100000}) = 0 (Timeout)
mkdir("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock", 0777) = -1 EEXIST (File exists)
stat("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock/dev0.-835f47008048", 0x7ffe07515b80) = -1 ENOENT (No such file or directory)
select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=100000}) = 0 (Timeout)
mkdir("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock", 0777) = -1 EEXIST (File exists)
stat("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock/dev0.-835f47008048", 0x7ffe07515b80) = -1 ENOENT (No such file or directory)
select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=100000}) = 0 (Timeout)
mkdir("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock", 0777) = -1 EEXIST (File exists)
stat("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock/dev0.-835f47008048", 0x7ffe07515b80) = -1 ENOENT (No such file or directory)
select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=100000}) = 0 (Timeout)
mkdir("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock", 0777) = -1 EEXIST (File exists)
stat("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock/dev0.-835f47008048", 0x7ffe07515b80) = -1 ENOENT (No such file or directory)
select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=100000}) = 0 (Timeout)
mkdir("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock", 0777) = -1 EEXIST (File exists)
stat("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock/dev0.-835f47008048", 0x7ffe07515b80) = -1 ENOENT (No such file or directory)
select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=100000}) = 0 (Timeout)
mkdir("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock", 0777) = -1 EEXIST (File exists)
stat("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock/dev0.-835f47008048", 0x7ffe07515b80) = -1 ENOENT (No such file or directory)
select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=100000}) = 0 (Timeout)
mkdir("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock", 0777) = -1 EEXIST (File exists)
stat("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock/dev0.-835f47008048", 0x7ffe07515b80) = -1 ENOENT (No such file or directory)
select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=100000}) = 0 (Timeout)
mkdir("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock", 0777) = -1 EEXIST (File exists)
stat("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock/dev0.-835f47008048", 0x7ffe07515b80) = -1 ENOENT (No such file or directory)
select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=100000}) = 0 (Timeout)
mkdir("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock", 0777) = -1 EEXIST (File exists)
stat("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock/dev0.-835f47008048", 0x7ffe07515b80) = -1 ENOENT (No such file or directory)
select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=100000}) = 0 (Timeout)
mkdir("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock", 0777) = -1 EEXIST (File exists)
stat("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock/dev0.-835f47008048", 0x7ffe07515b80) = -1 ENOENT (No such file or directory)
select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=100000}) = 0 (Timeout)
mkdir("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock", 0777) = -1 EEXIST (File exists)
stat("/srv/fieldagent/.cache/pip/http/1/e/6/f/2/1e6f2fa1119d47b853219feb91c3867d411e0c8c02476d1e769171e8.lock/dev0.-835f47008048", 0x7ffe07515b80) = -1 ENOENT (No such file or directory)
select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=100000}^Cstrace: Process 8048 detached
 <detached ...>
root@dev0:~#
```

Pipenv version: `'11.10.0'`

Pipenv location: `'/srv/fieldagent/.virtualenvs/fieldagent/local/lib/python2.7/site-packages/pipenv'`

Python location: `'/srv/fieldagent/.virtualenvs/fieldagent/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/srv/fieldagent/.virtualenvs/fieldagent/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/usr/bin/python3.5m`
  - `3.5`: `/usr/bin/python3.5`

  - `2.7.13`: `/srv/fieldagent/.virtualenvs/fieldagent/bin/python`
  - `2.7.13`: `/usr/bin/python`
  - `2.7.13`: `/srv/fieldagent/.virtualenvs/fieldagent/bin/python2`
  - `2.7.13`: `/usr/bin/python2`
  - `3.5.3`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.9.0-6-amd64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07)',
 'python_full_version': '2.7.13',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

Contents of `Pipfile` ('/srv/fieldagent/7g-backend/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
numpy = "*"
pandas = "==0.22.0"
pillow = "==4.3.0"
delorean = "==0.6.0"
dill = "==0.2.7.1"
eventlet = "==0.22.0"
flask = "*"
flask-admin = "==1.5.0"
flask-assets = "==0.12"
flask-bower = "==1.3.0"
flask-cors = "==3.0.3"
flask-jwt = "==0.3.2"
flask-login = "==0.4.1"
flask-mail = "==0.9.1"
flask-mongoengine = "==0.9.3"
flask-principal = "==0.4.0"
flask-script = "==2.0.6"
flask-security = "*"
flask-socketio = "==2.9.3"
flask-wtf = "==0.14.2"
geocoder = "==1.34.0"
gitpython = "==2.1.8"
gspread = "==0.6.2"
gunicorn = "==19.7.1"
imagehash = "==4.0"
"jinja2" = "==2.10"
kombu = "==4.1.0"
libipa = "==0.0.6"
mongoengine = "==0.15.0"
"oauth2client" = "==4.1.2"
openpyxl = "==2.5.0"
prettyprint = "==0.1.5"
pymongo = "==3.6.0"
python-dateutil = "*"
python-engineio = "==2.0.2"
python-magic = "==0.4.15"
python-socketio = "==1.8.4"
redis = "==2.10.6"
requests = "==2.18.4"
secretary = "==0.2.19"
werkzeug = "==0.14.1"
wtforms = "==2.1"
xlsxwriter = "==1.0.2"
htmlmin = "*"
"pypdf2" = "*"
flask-excel = "*"
pyexcel-xlsx = "*"
pyexcel-xls = "*"
cssmin = "*"
jsmin = "*"
flask-caching = "*"

```
