### ISSUE TITLE
Dependencies not installed for package using URL

### ISSUE THREAD

**Issue by dn0** [pypa/pipenv#2361]
Mentioning a package using a URL in Pipfile fails to install its dependencies.

Pipenv version: `'2018.05.18'`

Contents of `Pipfile`:

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
requests = {file = "https://github.com/requests/requests/tarball/master"}

[dev-packages]

[requires]
python_version = "3.6"
```

Contents of `Pipfile.lock`:

```json
{
    "_meta": {
        "hash": {
            "sha256": "4fed8c1756b3d13b305ed0759793cfbb51cdb3fad4638d16f3568fa53bac0863"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "requests": {
            "file": "https://github.com/requests/requests/tarball/master"
        }
    },
    "develop": {}
}
```

------------

### Expected result

```bash
$ pipenv install
Installing dependencies from Pipfile.lock (ac0863)…
...

$ pipenv run pip list
Package    Version  
---------- ---------
certifi    2018.4.16
chardet    3.0.4    
idna       2.7      
pip        10.0.1   
requests   2.19.1   
setuptools 39.2.0   
urllib3    1.23     
wheel      0.31.1 
```

### Actual result

```bash
$ pipenv install
Installing dependencies from Pipfile.lock (ac0863)…
...

 $ pipenv run pip list
Package    Version
---------- -------
pip        10.0.1 
requests   2.19.1 
setuptools 39.2.0 
wheel      0.31.1 
```
