### ISSUE TITLE
Unexpected Dependancy Graph Issue

### ISSUE THREAD

**Issue by JBKahn** [pypa/pipenv#2529]
##### Issue description

I had a requirement pinned to "<4.0.0" and a sub-dependancy that required it to be "==3.3.0". I checked the graph and as expected, that was the only dependancy that required the protobuf package.

That gave me a dependancy resolution error of:
`Could not find a version that matches protobuf<4.0.0,==3.3.0,==3.6.0` 

##### Expected result

I expected it to resolve to "==3.3.0"

##### Actual result

I was able to get it to be happy by changing my local "<4.0.0" to "==3.3.0".

##### Steps to replicate

I will fill this is later today, but wanted to spell out the issue just in case it is known.

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

**Comment by erinxocon** [comment]
Hey @JBKahn Any update on this?

**Comment by JBKahn** [comment]
I had been slammed at work, it seems to be possibly related to my build environment as this didn't happen on my machine but inside an alpine python docker container. Was going to dig in before I included all the details.

**Comment by teeberg** [comment]
I think I'm experiencing the same issue with a different package:

> Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
>   You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
>   Hint: try $ pipenv lock --pre if it is a pre-release dependency.
> Could not find a version that matches botocore<1.11.0,==1.10.26,>=1.10.26,>=1.10.64 (from -r /var/folders/h4/n2jm49b97dx5d89gkkt4yxkm0000gn/T/pipenv-KF21xr-requirements/pipenv-Vk6UhE-constraints.txt (line 34))

and it's true, `==1.10.26` and `>=1.10.64` contradict themselves, but no package seems to be pulling in `>=1.10.64`?!

After running the suggested `pipenv install --skip-lock` and inspecting the output of `pipenv graph`, here are botocore's dependency specs:

```
> pipenv graph | grep -i botocore
  - botocore [required: ==1.10.26, installed: 1.10.26]
    - botocore [required: >=1.3.0,<2.0.0, installed: 1.10.26]
  - botocore [required: >=1.0.1, installed: 1.10.26]
    - botocore [required: >=1.10.26,<1.11.0, installed: 1.10.26]
      - botocore [required: >=1.3.0,<2.0.0, installed: 1.10.26]
```

I'm just investigating how much work it is to switch over to using `pipenv` from a workflow using `pip-compile`, so I have another virtual env set up with exactly these requirements as specified, and using `pipdeptree` in there doesn't show anything specifying `>=1.10.64` either:
```
> pipdeptree -r -p botocore | grep "requires: botocore"
  - awscli==1.15.26 [requires: botocore==1.10.26]
  - awsebcli==3.14.3 [requires: botocore>=1.0.1]
  - boto3==1.7.26 [requires: botocore>=1.10.26,<1.11.0]
  - s3transfer==0.1.12 [requires: botocore>=1.3.0,<2.0.0]
```

So, maybe this comes down to, how do I find out where that bogus version spec comes from?

**Comment by JBKahn** [comment]
yeah, the real difficulty is that when there is a collision, the output isn't showing where the different requirements come from. I've been super busy these past few days but I'll try to get to this ASAP.

**Comment by mr-bo-jangles** [comment]
> yeah, the real difficulty is that when there is a collision, the output isn't showing where the different requirements come from

Literally dealing with this right now, it's impossible to track down which package is causing issues

**Comment by mr-bo-jangles** [comment]
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/home/josh/.virtualenvs/savings-champion/lib/python3.6/site-packages/pipenv'`

Python location: `'/home/josh/.virtualenvs/savings-champion/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/home/josh/.virtualenvs/savings-champion/bin/python3.6`
  - `3.6`: `/usr/bin/python3.6`

  - `3.6.6`: `/home/josh/.virtualenvs/savings-champion/bin/python`
  - `3.6.6`: `/usr/bin/python`
  - `2.7.15`: `/usr/bin/python2`
  - `3.6.6`: `/home/josh/.virtualenvs/savings-champion/bin/python3`
  - `3.6.6`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.6',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.17.11-arch1',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT Sun Jul 29 10:11:16 UTC 2018',
 'python_full_version': '3.6.6',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `PATH`
  - `XAUTHORITY`
  - `GDMSESSION`
  - `XDG_DATA_DIRS`
  - `ZDOTDIR`
  - `KDE_SESSION_UID`
  - `TERM`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `LANG`
  - `XDG_SESSION_TYPE`
  - `XDG_SESSION_ID`
  - `XDG_CURRENT_DESKTOP`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `DISPLAY`
  - `MAIL`
  - `MOZ_PLUGIN_PATH`
  - `SESSION_MANAGER`
  - `USERNAME`
  - `LOGNAME`
  - `PWD`
  - `_`
  - `XCURSOR_THEME`
  - `LANGUAGE`
  - `KDE_SESSION_VERSION`
  - `SHELL`
  - `GDM_LANG`
  - `XCURSOR_SIZE`
  - `DESKTOP_SESSION`
  - `OLDPWD`
  - `USER`
  - `DESKTOP_STARTUP_ID`
  - `KDE_FULL_SESSION`
  - `WINDOWPATH`
  - `XDG_SEAT`
  - `GTK_MODULES`
  - `GS_LIB`
  - `LC_ALL`
  - `KWIN_TRIPLE_BUFFER`
  - `XDG_RUNTIME_DIR`
  - `XDG_SESSION_DESKTOP`
  - `XDG_VTNR`
  - `SHLVL`
  - `HOME`
  - `EDITOR`
  - `VISUAL`
  - `PAGER`
  - `LESS`
  - `LESS_TERMCAP_mb`
  - `LESS_TERMCAP_md`
  - `LESS_TERMCAP_me`
  - `LESS_TERMCAP_se`
  - `LESS_TERMCAP_so`
  - `LESS_TERMCAP_ue`
  - `LESS_TERMCAP_us`
  - `LS_COLORS`
  - `GREP_COLOR`
  - `GREP_COLORS`
  - `VIRTUAL_ENV`
  - `PS1`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:


Debug–specific environment variables:

  - `PATH`: `/home/josh/.virtualenvs/savings-champion/bin:/usr/local/bin:/usr/local/sbin:/home/josh/go/bin:/home/josh/.yarn/bin:/usr/bin:/opt/cuda/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
  - `SHELL`: `/usr/bin/zsh`
  - `EDITOR`: `nano`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/home/josh/PycharmProjects/savings-champion`
  - `VIRTUAL_ENV`: `/home/josh/.virtualenvs/savings-champion`


---------------------------

Contents of `Pipfile` ('/home/josh/PycharmProjects/savings-champion/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
lxml = "*"
nose = "*"
django-extensions = "*"
django-tinymce = "*"
sorl-thumbnail = "*"
"suds-py3" = "*"
feedparser = "*"
python-dateutil = "*"
python-memcached = "*"
django-pipeline = "*"
requests = "*"
django-pipeline-forgiving = "*"
django-ckeditor = "*"
django-filebrowser = "*"
raven = "*"
celery = {version = "*", extras = ["redis"]}
"psycopg2-binary" = "*"
django-crispy-forms = "*"
pyotp = "*"
newrelic = "*"
djangorestframework = "*"
djangorestframework-xml = "*"
djangorestframework-jwt = "*"
django-filter = "*"
parsedatetime = "*"
simple-salesforce = "*"
django-allauth = "*"
apache-libcloud = "*"
django-storages = "*"
"boto3" = "*"
sortedcontainers = "*"
redis = "*"
hiredis = "*"
msgpack-python = "*"
django-waffle = "*"
django-report-builder = "*"
django-markupfield = "*"
django-cors-headers = "*"
arrow = "*"
django-redis = "*"
"mailchimp3" = "*"
dotmailer = {editable = true, git = "https://github.com/savingschampion/dotmailer.git"}
simplejson = "*"
zeep = "*"
djangorestframework-jsonp = "*"
requests-oauthlib = "*"
django-ipware = "*"
hypothesis = {version = "*", extras = ["pytz"]}
drf-yasg = {version = "*", extras = ["validation"]}
Django = ">=2.0"
Pillow = "*"
uWSGI = "*"
"Django-Select2" = "*"
Collectfast = "*"
Markdown = "*"
Faker = "*"
rest_condition = "*"
django-rest-knox = "*"
django-simple-history = "*"
wagtail = "*"
wagtail-metadata-mixin = "*"

[dev-packages]

[requires]
python_version = "3.6"

```

</details>
