### ISSUE TITLE
Installing coverage deletes Pipfile.lock without any warning

### ISSUE THREAD

**Issue by petarGitNik** [pypa/pipenv#2761]
##### Issue description

Installing coverage.py with pipenv removes Pipfile.lock without any warning.

##### Expected result

Pipfile.lock updated with new package, and still existing.

##### Actual result

```bash
$ pipenv install coverage --dev
Installing coverage…
Looking in indexes: https://pypi.python.org/simple
Collecting coverage
  Using cached https://files.pythonhosted.org/packages/2c/c0/8047b7cbbcdbd7d21f8d68126196b7915da892c5af3d1a99dba082d33ec0/coverage-4.5.1-cp35-cp35m-manylinux1_x86_64.whl
Installing collected packages: coverage
Successfully installed coverage-4.5.1

Adding coverage to Pipfile's [dev-packages]…
Pipfile.lock (c2b9f3) out of date, updating to (7ba9e7)…
Locking [dev-packages] dependencies…
```

##### Steps to replicate

The `Pipfile`:

```toml
[[source]]
verify_ssl = true
name = "pypi"
url = "https://pypi.python.org/simple"

[dev-packages]
django-cors-headers = "*"
"flake8" = "*"
pycodestyle = "*"

[packages]
django = "*"
lti = "*"
"psycopg2-binary" = "*"
oauthlib = "*"
djangorestframework = "*"
"4acce62" = {path = "./apiwrapper-0.2.1-py3-none-any.whl"}

[requires]
python_version = "3.5"
```

The command:

```
pipenv install coverage --dev
```

My environment:

* Python 3.5.2
* pipenv, version 11.9.0
* Ubuntu 16.04
