### ISSUE TITLE
Chaining Script Commands

### ISSUE THREAD

**Issue by jamesstidard** [pypa/pipenv#2878]
Hi,

I was just wondering, for the `[scripts]` feature, how best I might inline a few commands. I'm looking to do things like for `pipenv run deploy` for it to first call a `build` script:

```toml
[scrips]
docs-build = "sphinx-build -b html docs docs/_build"
docs-deploy = "pipenv run docs-build && aws s3 sync docs/_build"
```

The way I've found to do this, is to do something like:

```toml
[scrips]
docs-build = "sphinx-build -b html docs docs/_build"
docs-deploy = "bash -c 'pipenv run docs-build && aws s3 sync docs/_build'"
```

I was wondering if there was a cleaner way of listing scripts that I've not thought of, like if scripts can take a list or undocumented `pre-/post-` command syntax. Just wanted to check as using bash might just add a dependency I don't need for platforms like Windows.

Thanks
