### ISSUE TITLE
pipenv install fails

### ISSUE THREAD

**Issue by kkrisz** [pypa/pipenv#2938]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://docs.pipenv.org/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

When trying to setup up initial environment with existing Pipfile pipenv fails.

### Expected result

Environment setup without error messages

### Actual result

pipenv install
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
c/lib/python3.7/site-packages/pipenv/utils.py", line 250, in actually_resolve_deps
    req = Requirement.from_line(dep)
  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 704, in from_line
    line, extras = _strip_extras(line)
TypeError: 'module' object is not callable
/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv/_compat.py:113: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/var/folders/mp/b93ljg_s0n51x5rfggyh49f40000gn/T/pipenv-Q5KqF6-requirements'>
  warnings.warn(warn_message, ResourceWarning)

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by kkrisz** [comment]
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2018.7.1/libexec/bin/python3.7'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/usr/local/bin/python3.5m`
  - `3.5`: `/usr/local/bin/python3.5`
  - `3.7`: `/usr/local/bin/python3.7m`
  - `3.7`: `/usr/local/bin/python3.7`

  - `2.7.15`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.15`: `/usr/local/bin/python2`
  - `3.7.0`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.0.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT '
                     '2018; root:xnu-4903.201.2~1/RELEASE_X86_64',
 'python_full_version': '3.7.0',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `TERM_PROGRAM`
  - `TERM`
  - `SHELL`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `KRDIR`
  - `_`
  - `PWD`
  - `LANG`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `HOME`
  - `SHLVL`
  - `LOGNAME`
  - `__CF_USER_TEXT_ENCODING`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:


Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2018.7.1/libexec/tools:/Users/krisz/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.local/bin/:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Postgres.app/Contents/Versions/latest/bin:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_AU.UTF-8`
  - `PWD`: `/Users/krisz/Development/ZUUS`


---------------------------

Contents of `Pipfile` ('/Users/krisz/Development/ZUUS/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]
mock = "*"
freezegun = "*"
factory_boy = "==2.8.1"
"hypothesis[django]" = "*"
Faker = "*"
tblib = "*"
django-coverage-plugin = {git = "https://github.com/nedbat/django_coverage_plugin.git", editable = true}

[packages]
pycparser = "==2.14"                        # Can't unpin because this package can't be updated (already installed).
Django = "==1.11.15"
"psycopg2-binary" = "*"
celery = "==3.1.25"
dj-database-url = "*"
django-cache-url = "*"
django-classy-settings = "==2.0.1"          # Can't unpin this until Python3
sqlparse = "*"
Pygments = "*"
raven = "*"
django-countries = "*"
django-mptt = "*"
django-widget-tweaks = "*"
django-celery = "*"
django-celery-email = "==1.1.5"             # Can't unpin this until Celery 4
django-ckeditor = "*"
django-wysiwyg = "*"
django-cors-headers = "*"
django-reversion = "==2.0.13"               # Can't unpin without extra work (they changed migrations).
django-sniplates = "*"
django-waffle = "*"
django-rest-framework = "*"
social-auth-app-django = "==2.1.0"          # This triggers some errors.
django-impersonate = "*"
pathlib = "*"
unicodecsv = "*"
"iso-8601" = "*"
isoweek = "*"
newrelic = "*"
paramiko = "*"
django-timezone-field = "*"
weasyprint = "==0.36"
django-model-utils = "==3.0.0"
django-redis = "*"
wrapt = "*"
django-picklefield = "*"
django-localflavor = "*"
py_lru_cache = "*"
pygeoip = "*"
BeautifulSoup = "*"
xlrd = "*"
pycrypto = "*"
attrs = "*"
rinse = "*"
SOAPpy = "*"
xmltodict = "*"
times = "*"
djangorestframework-jwt = "*"
django-filtered-form = "*"
django-formtools = "*"
django-storages = "*"
"boto3" = "*"
suds = "*"
protobuf = "*"
whitenoise = "*"
boto = "*"
IMAPClient = "*"
"flufl.bounce" = "==2.3"                # Can't unpin this until Python3.
django-markup-deprecated = "*"
selenium = "*"
xlwt = "*"
django-extensions = "*"
wagtail = "==1.12.2"
django-gevent-websocket = "*"
markdown = "*"
sparkpost = "*"
gunicorn = "*"
gevent = "==1.2.1"                         # Must be this version for gevent websocket.

[requires]
python_full_version = "2.7.15"

```

</details>
