### ISSUE TITLE
Pipenv tries to lock/install libraries that are platform dependent, on wrong platform

### ISSUE THREAD

**Issue by AndreiH** [pypa/pipenv#3187]
### Issue description

When running `pipenv install` on Linux\Windows,  Pipenv tries to install/lock also the Darwin specific dependencies and the `Locking...` of the dependencies fails.

The same error I get also when using `pip install pyobjc` (pyobjc being the Darwin only dependency), and I get the same error.  This suggesting that `Pipenv` tries to install the dependency.

Using the latest version: **pipenv, version 2018.10.14.dev0**

### Expected result

Pipenv should lock dependencies without errors.

### Actual result

```
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
✘ Locking Failed! 
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  coloredlogs==10.0
   (from -r /tmp/pipenvH_f_dyrequirements/pipenv-QsCfk9-constraints.txt (line 33))
  gitpython==2.1.11
  image==1.5.27
  mozdownload==1.25
  mozinfo==1.0.0
  mozinstall==1.16.0
  mozrunner==7.2.0
  mozversion==1.5
  mss==3.3.1
  numpy==1.15.4
  opencv-python==3.4.1.15
  packaging==18.0
  pep8
  pyautogui==0.9.38
  pynput==1.4
  pyobjc==5.1.1
  pyobjc-core==5.1.1
  pyobjc-framework-addressbook
  pyobjc-framework-cfnetwork
  pyobjc-framework-cocoa
  pyobjc-framework-coreaudio
  pyobjc-framework-coreaudiokit
  pyobjc-framework-coredata
  pyobjc-framework-corelocation
  pyobjc-framework-coreservices
  pyobjc-framework-coretext
  pyobjc-framework-corewlan
  pyobjc-framework-discrecording
  pyobjc-framework-fsevents
  pyobjc-framework-imagecapturecore
  pyobjc-framework-inputmethodkit
  pyobjc-framework-qtkit
  pyobjc-framework-quartz
  pyobjc-framework-screensaver
  pyobjc-framework-scriptingbridge
  pyobjc-framework-security
  pyobjc-framework-securityinterface
  pyobjc-framework-syncservices
  pyobjc-framework-systemconfiguration
  pyobjc-framework-webkit
  pyperclip==1.7.0
  pytesseract==0.2.5
  python-dateutil==2.7.5
  xlib==0.21

Finding the best candidates:
  found candidate coloredlogs==10.0 (constraint was ==10.0)
  found candidate -e file:///home//iris (constraint was <any>)
  found candidate gitpython==2.1.11 (constraint was ==2.1.11)
  found candidate image==1.5.27 (constraint was ==1.5.27)
  found candidate mozdownload==1.25 (constraint was ==1.25)
  found candidate mozinfo==1.0.0 (constraint was ==1.0.0)
  found candidate mozinstall==1.16.0 (constraint was ==1.16.0)
  found candidate mozrunner==7.2.0 (constraint was ==7.2.0)
  found candidate mozversion==1.5 (constraint was ==1.5)
  found candidate mss==3.3.1 (constraint was ==3.3.1)
  found candidate numpy==1.15.4 (constraint was ==1.15.4)
  found candidate opencv-python==3.4.1.15 (constraint was ==3.4.1.15)
  found candidate packaging==18.0 (constraint was ==18.0)
  found candidate pep8==1.7.1 (constraint was <any>)
  found candidate pyautogui==0.9.38 (constraint was ==0.9.38)
  found candidate pynput==1.4 (constraint was ==1.4)
  found candidate pyobjc==5.1.1 (constraint was ==5.1.1)
  found candidate pyobjc-core==5.1.1 (constraint was ==5.1.1)
  found candidate pyobjc-framework-addressbook==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-cfnetwork==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-cocoa==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-coreaudio==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-coreaudiokit==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-coredata==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-corelocation==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-coreservices==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-coretext==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-corewlan==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-discrecording==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-fsevents==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-imagecapturecore==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-inputmethodkit==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-qtkit==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-quartz==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-screensaver==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-scriptingbridge==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-security==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-securityinterface==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-syncservices==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-systemconfiguration==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-webkit==5.1.1 (constraint was <any>)
  found candidate pyperclip==1.7.0 (constraint was ==1.7.0)
  found candidate pytesseract==0.2.5 (constraint was ==0.2.5)
  found candidate python-dateutil==2.7.5 (constraint was ==2.7.5)
  found candidate xlib==0.21 (constraint was ==0.21)

Finding secondary dependencies:
  pyobjc-framework-corelocation==5.1.1 not in cache, need to check index
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 121, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 114, in main
    parsed.requirements_dir, parsed.packages)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 597, in resolve_deps
    req_dir=req_dir,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 450, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 407, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 474, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpOaIdE3build/pyobjc-framework-corelocation/
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  coloredlogs==10.0
  file:///home/iris (from -r /tmp/pipenvH_f_dyrequirements/pipenv-QsCfk9-constraints.txt (line 33))
  gitpython==2.1.11
  image==1.5.27
  mozdownload==1.25
  mozinfo==1.0.0
  mozinstall==1.16.0
  mozrunner==7.2.0
  mozversion==1.5
  mss==3.3.1
  numpy==1.15.4
  opencv-python==3.4.1.15
  packaging==18.0
  pep8
  pyautogui==0.9.38
  pynput==1.4
  pyobjc==5.1.1
  pyobjc-core==5.1.1
  pyobjc-framework-addressbook
  pyobjc-framework-cfnetwork
  pyobjc-framework-cocoa
  pyobjc-framework-coreaudio
  pyobjc-framework-coreaudiokit
  pyobjc-framework-coredata
  pyobjc-framework-corelocation
  pyobjc-framework-coreservices
  pyobjc-framework-coretext
  pyobjc-framework-corewlan
  pyobjc-framework-discrecording
  pyobjc-framework-fsevents
  pyobjc-framework-imagecapturecore
  pyobjc-framework-inputmethodkit
  pyobjc-framework-qtkit
  pyobjc-framework-quartz
  pyobjc-framework-screensaver
  pyobjc-framework-scriptingbridge
  pyobjc-framework-security
  pyobjc-framework-securityinterface
  pyobjc-framework-syncservices
  pyobjc-framework-systemconfiguration
  pyobjc-framework-webkit
  pyperclip==1.7.0
  pytesseract==0.2.5
  python-dateutil==2.7.5
  xlib==0.21

Finding the best candidates:
  found candidate coloredlogs==10.0 (constraint was ==10.0)
  found candidate -e file:///home/iris (constraint was <any>)
  found candidate gitpython==2.1.11 (constraint was ==2.1.11)
  found candidate image==1.5.27 (constraint was ==1.5.27)
  found candidate mozdownload==1.25 (constraint was ==1.25)
  found candidate mozinfo==1.0.0 (constraint was ==1.0.0)
  found candidate mozinstall==1.16.0 (constraint was ==1.16.0)
  found candidate mozrunner==7.2.0 (constraint was ==7.2.0)
  found candidate mozversion==1.5 (constraint was ==1.5)
  found candidate mss==3.3.1 (constraint was ==3.3.1)
  found candidate numpy==1.15.4 (constraint was ==1.15.4)
  found candidate opencv-python==3.4.1.15 (constraint was ==3.4.1.15)
  found candidate packaging==18.0 (constraint was ==18.0)
  found candidate pep8==1.7.1 (constraint was <any>)
  found candidate pyautogui==0.9.38 (constraint was ==0.9.38)
  found candidate pynput==1.4 (constraint was ==1.4)
  found candidate pyobjc==5.1.1 (constraint was ==5.1.1)
  found candidate pyobjc-core==5.1.1 (constraint was ==5.1.1)
  found candidate pyobjc-framework-addressbook==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-cfnetwork==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-cocoa==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-coreaudio==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-coreaudiokit==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-coredata==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-corelocation==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-coreservices==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-coretext==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-corewlan==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-discrecording==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-fsevents==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-imagecapturecore==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-inputmethodkit==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-qtkit==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-quartz==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-screensaver==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-scriptingbridge==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-security==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-securityinterface==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-syncservices==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-systemconfiguration==5.1.1 (constraint was <any>)
  found candidate pyobjc-framework-webkit==5.1.1 (constraint was <any>)
  found candidate pyperclip==1.7.0 (constraint was ==1.7.0)
  found candidate pytesseract==0.2.5 (constraint was ==0.2.5)
  found candidate python-dateutil==2.7.5 (constraint was ==2.7.5)
  found candidate xlib==0.21 (constraint was ==0.21)

Finding secondary dependencies:
  pyobjc-framework-corelocation==5.1.1 not in cache, need to check index
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 121, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 114, in main
    parsed.requirements_dir, parsed.packages)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 597, in resolve_deps
    req_dir=req_dir,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 450, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 407, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 474, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpOaIdE3build/pyobjc-framework-corelocation/
```

### Steps to replicate

1. Pipenv contains liraries which are platform dependent:
**It seems that it only has to do with `pyobjc` Darwin specific dependencies**
```
xlib = {version = "==0.21", platform_system = "== 'Linux'"}
pyobjc = {version = "==5.1.1", platform_system = "== 'Darwin'"}
pyobjc-core = {version = "==5.1.1", platform_system = "== 'Darwin'"}
```
2. Run `pipenv install`

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.10.14.dev0'`

Pipenv location: `'/usr/local/lib/python2.7/dist-packages/pipenv'`

Python location: `'/usr/bin/python'`

Python installations found:

  - `3.6.6`: `/usr/bin/python3.6`
  - `3.6.6`: `/usr/bin/python3.6m`
  - `2.7.15rc1`: `/usr/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-38-generic',
 'platform_system': 'Linux',
 'platform_version': '#41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018',
 'python_full_version': '2.7.15rc1',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `USERNAME`
  - `MANDATORY_PATH`
  - `LC_NUMERIC`
  - `GNOME_DESKTOP_SESSION_ID`
  - `LC_CTYPE`
  - `WINDOWPATH`
  - `XDG_CURRENT_DESKTOP`
  - `LC_PAPER`
  - `QT_IM_MODULE`
  - `LOGNAME`
  - `USER`
  - `HOME`
  - `XDG_VTNR`
  - `PATH`
  - `VIRTUALENVWRAPPER_SCRIPT`
  - `ZSH`
  - `DISPLAY`
  - `SSH_AGENT_PID`
  - `LANG`
  - `TERM`
  - `SHELL`
  - `XAUTHORITY`
  - `SESSION_MANAGER`
  - `SHLVL`
  - `QT_QPA_PLATFORMTHEME`
  - `QT_ACCESSIBILITY`
  - `QT4_IM_MODULE`
  - `CLUTTER_IM_MODULE`
  - `TEXTDOMAIN`
  - `GNOME_TERMINAL_SERVICE`
  - `DESKTOP_AUTOSTART_ID`
  - `IM_CONFIG_PHASE`
  - `VIRTUALENVWRAPPER_HOOK_DIR`
  - `GPG_AGENT_INFO`
  - `LC_MONETARY`
  - `GTK2_MODULES`
  - `XDG_SESSION_DESKTOP`
  - `XDG_RUNTIME_DIR`
  - `WORKON_HOME`
  - `LC_IDENTIFICATION`
  - `LC_ADDRESS`
  - `PIP_SHIMS_BASE_MODULE`
  - `SSH_AUTH_SOCK`
  - `VTE_VERSION`
  - `GDMSESSION`
  - `XMODIFIERS`
  - `TEXTDOMAINDIR`
  - `GNOME_SHELL_SESSION_MODE`
  - `PYTHONDONTWRITEBYTECODE`
  - `XDG_DATA_DIRS`
  - `LC_ALL`
  - `PIP_PYTHON_PATH`
  - `XDG_SESSION_ID`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `_`
  - `GTK_MODULES`
  - `GTK_IM_MODULE`
  - `DESKTOP_SESSION`
  - `LSCOLORS`
  - `XDG_CONFIG_DIRS`
  - `DEFAULTS_PATH`
  - `XDG_SESSION_TYPE`
  - `XDG_SEAT`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `OLDPWD`
  - `VIRTUALENVWRAPPER_PROJECT_FILENAME`
  - `LS_COLORS`
  - `LC_TELEPHONE`
  - `LC_MEASUREMENT`
  - `PWD`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `COLORTERM`
  - `LC_NAME`
  - `XDG_MENU_PREFIX`
  - `LC_TIME`
  - `LESS`
  - `PAGER`
  - `VIRTUALENVWRAPPER_WORKON_CD`
  - `GNOME_TERMINAL_SCREEN`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/usr/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/user/iris`

---------------------------

Contents of `Pipfile` ('/home/user/iris/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
iris = {path = ".", editable = true}
pyautogui = "==0.9.38"
coloredlogs = "==10.0"
python-dateutil = "==2.7.5"
opencv-python = "==3.4.1.15"
pytesseract = "==0.2.5"
numpy = "==1.15.4"
image = "==1.5.27"
pyperclip = "==1.7.0"
packaging = "==18.0"
gitpython = "==2.1.11"
pynput = "==1.4"
mozinstall = "==1.16.0"
mozdownload = "==1.25"
mozversion = "==1.5"
mozinfo = "==1.0.0"
mozrunner = "==7.2.0"
mss = "==3.3.1"
pep8 = "*"
# Platform dependencies
xlib = {version = "==0.21", platform_system = "== 'Linux'"}
pyobjc = {version = "==5.1.1", platform_system = "== 'Darwin'"}
pyobjc-core = {version = "==5.1.1", platform_system = "== 'Darwin'"}
pyobjc-framework-quartz = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-cocoa = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-webkit = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-screensaver = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-discrecording = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-syncservices = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-coretext = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-systemconfiguration = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-coreaudiokit = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-securityinterface = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-security = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-coreaudio = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-coreservices = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-coredata = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-cfnetwork = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-addressbook = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-imagecapturecore = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-corewlan = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-corelocation = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-qtkit = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-scriptingbridge = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-fsevents = {version = "*", platform_system = "== 'Darwin'"}
pyobjc-framework-inputmethodkit = {version = "*", platform_system = "== 'Darwin'"}

[dev-packages]

[requires]
python_version = "2.7"

```

</details>
