### ISSUE TITLE
Dependencies couldn't be resolved, even with "pipenv lock --clear"

### ISSUE THREAD

**Issue by bclayman** [pypa/pipenv#3347]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

I'm using pipenv version '2018.7.1' along with pip 18.0.  I'm trying to run "pipenv install" with a Pipfile that looks like:

```toml
[[source]]

url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]

pandas = "*"
scikit-learn = "==0.19.0"
spacy = "*"
numpy = "*"
scipy = "*"
jupyter = "*"
nltk = "*"
cookiecutter = "*"
mistune = "*"
"beautifulsoup4" = "*"
colorlog = "*"

[requires]

python_version = "2.7"
```

### Issue description

When I run `pipenv install` I get:

```
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches prompt-toolkit<2.0.0,<2.1.0,==2.0.7,>=1.0.0,>=1.0.4,>=2.0.0
Tried: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.25, 0.26, 0.28, 0.30, 0.31, 0.32, 0.32, 0.32, 0.33, 0.33, 0.33, 0.34, 0.34, 0.34, 0.35, 0.35, 0.35, 0.36, 0.36, 0.36, 0.37, 0.37, 0.37, 0.38, 0.38, 0.38, 0.39, 0.39, 0.39, 0.40, 0.40, 0.40, 0.41, 0.41, 0.41, 0.42, 0.42, 0.42, 0.43, 0.43, 0.43, 0.44, 0.44, 0.44, 0.45, 0.45, 0.45, 0.46, 0.46, 0.46, 0.47, 0.47, 0.47, 0.48, 0.48, 0.48, 0.49, 0.49, 0.49, 0.50, 0.50, 0.50, 0.51, 0.51, 0.51, 0.52, 0.52, 0.52, 0.53, 0.53, 0.53, 0.54, 0.54, 0.54, 0.55, 0.55, 0.55, 0.56, 0.56, 0.56, 0.57, 0.57, 0.57, 0.58, 0.58, 0.58, 0.59, 0.59, 0.59, 0.60, 0.60, 0.60, 1.0.0, 1.0.0, 1.0.0, 1.0.1, 1.0.1, 1.0.1, 1.0.2, 1.0.2, 1.0.2, 1.0.3, 1.0.3, 1.0.3, 1.0.4, 1.0.4, 1.0.4, 1.0.5, 1.0.5, 1.0.5, 1.0.6, 1.0.6, 1.0.6, 1.0.7, 1.0.7, 1.0.7, 1.0.8, 1.0.8, 1.0.8, 1.0.9, 1.0.9, 1.0.9, 1.0.10, 1.0.10, 1.0.10, 1.0.13, 1.0.13, 1.0.13, 1.0.14, 1.0.14, 1.0.14, 1.0.15, 1.0.15, 1.0.15, 2.0.1, 2.0.1, 2.0.1, 2.0.2, 2.0.2, 2.0.2, 2.0.3, 2.0.3, 2.0.3, 2.0.4, 2.0.4, 2.0.4, 2.0.5, 2.0.5, 2.0.5, 2.0.6, 2.0.6, 2.0.6, 2.0.7, 2.0.7, 2.0.7
There are incompatible versions in the resolved dependencies.
```

### Expected result

I'd expect this to install properly without errors.  Also, I wouldn't expect a dependency issue from `prompt-toolkit` since when I run `pipenv graph`, I see:

`- prompt-toolkit [required: >=1.0.4,<2.0.0, installed: 1.0.15]`

for all of the dependencies that reference `prompt-toolkit`.  So I'm surprised to see:

`Could not find a version that matches prompt-toolkit<2.0.0,<2.1.0,==2.0.7,>=1.0.0,>=1.0.4,>=2.0.0`

### Actual result

 I went through the [diagnose documentation](https://docs.pipenv.org/diagnose/) and tried `pipenv lock --clear` in addition to clearing my cache but that doesn't fix the above issue.

### Steps to replicate

1) Create Pipfile as described above.
2) Run pipenv install
