### ISSUE TITLE
2.7 is written into Pipfile even python is explicitly given.

### ISSUE THREAD

**Issue by frostming** [pypa/pipenv#3393]
### Issue description

As title

### Expected result

`[python_requires]` shows the correct python picked.

### Actual result

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "2.7"
```

### Steps to replicate

1. Start a clean docker container from `kennethreitz:pipenv-tests`
2. `pip install -U -e .`
3. Go to a new dir and execute: `pipenv install`

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "2.7"
root@1e1fba85aa16:/temp# pipenv --support
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.27.dev0'`

Pipenv location: `'/pipenv/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.6.5`: `/usr/bin/python3.6`
  - `3.6.5`: `/usr/bin/python3.6m`
  - `2.7.15rc1`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.9.125-linuxkit',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Fri Sep 7 08:20:28 UTC 2018',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LC_ALL`
  - `LS_COLORS`
  - `HTTP_PROXY`
  - `LESSCLOSE`
  - `LANG`
  - `HOSTNAME`
  - `PWD`
  - `HOME`
  - `https_proxy`
  - `http_proxy`
  - `HTTPS_PROXY`
  - `TERM`
  - `SHLVL`
  - `PATH`
  - `LESSOPEN`
  - `_`
  - `OLDPWD`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/temp`

---------------------------

Contents of `Pipfile` ('/temp/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "2.7"

```
