### ISSUE TITLE
pipenv graph does not show all top-level packages

### ISSUE THREAD

**Issue by thernstig** [pypa/pipenv#3460]
### Issue description

My Pipfile contains the following:

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
requests = "*"

[requires]
python_version = "2.7"
```

Pipenv graph then shows the output:

```sh
requests==2.21.0
  - certifi [required: >=2017.4.17, installed: 2018.11.29]
  - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
  - idna [required: >=2.5,<2.9, installed: 2.8]
  - urllib3 [required: >=1.21.1,<1.25, installed: 1.24.1]
```

I add another package under [dev-packages]:

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
sphinx-rtd-theme = "*"

[packages]
requests = "*"

[requires]
python_version = "2.7"
```

Since `sphinx-rtd-theme` has a dependency towards `requests`, the graph now only shows `requests` underneath `sphinx-rtd-theme`.

```sh
sphinx-rtd-theme==0.4.2
  - sphinx [required: Any, installed: 1.8.3]
    - alabaster [required: >=0.7,<0.8, installed: 0.7.12]
    - babel [required: >=1.3,!=2.0, installed: 2.6.0]
      - pytz [required: >=0a, installed: 2018.9]
    - docutils [required: >=0.11, installed: 0.14]
    - imagesize [required: Any, installed: 1.1.0]
    - Jinja2 [required: >=2.3, installed: 2.10]
      - MarkupSafe [required: >=0.23, installed: 1.1.0]
    - packaging [required: Any, installed: 18.0]
      - pyparsing [required: >=2.0.2, installed: 2.3.1]
      - six [required: Any, installed: 1.12.0]
    - Pygments [required: >=2.0, installed: 2.3.1]
    - requests [required: >=2.0.0, installed: 2.21.0]
      - certifi [required: >=2017.4.17, installed: 2018.11.29]
      - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
      - idna [required: >=2.5,<2.9, installed: 2.8]
      - urllib3 [required: >=1.21.1,<1.25, installed: 1.24.1]
    - setuptools [required: Any, installed: 40.6.3]
    - six [required: >=1.5, installed: 1.12.0]
    - snowballstemmer [required: >=1.1, installed: 1.2.1]
    - sphinxcontrib-websupport [required: Any, installed: 1.1.0]
    - typing [required: Any, installed: 3.6.6]
```

### Expected result

I expected `requests` to also be shown at the top level, as it is a top-level dependency. The reason why I expect this is that other dependencies are shown multiple times. Look at for example `six` shown twice above.

I assume that it is reasonable to show main packages at the top and then also as again if it is a dependency of other packages.

### Steps to replicate

1. Start in a fresh directory and call `pipenv install requests`
2. Check `pipenv graph`
3. Run `pipenv install --dev sphinx-rtd-theme`
4. Check `pipenv graph`
