### ISSUE TITLE
Allow command line arguments to be defaulted from Pipfile.

### ISSUE THREAD

**Issue by thomasf** [pypa/pipenv#3700]
When working in many projects with lots of other people I have seen that I have to who might not know or understand the implications of  all the details of how pipenv works,  some people are just programmers and should not have to be bothered by these details. 

I would as an example like that `pipenv install` were always by default running with `--keep-outdated` and  maybe `--selective-upgrade` unless otherwise specified in a lot of projects.  

Maybe a `[pipenv]` section in the Pipfile?

```toml
[pipenv]
selective_upgrade = true # applies to all possible sub commands which uses selective upgrade
install__keep_outdated = true # applies specifically to the `install` sub command 
# ...
```

Direct use of command line flags or environment variables should still override settings made in Pipfile.
