### ISSUE TITLE
ERROR: ERROR: Could not find a version that matches requirements-txt

### ISSUE THREAD

**Issue by GhalyahF** [pypa/pipenv#3705]
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/Users/ghalyahalansari/anaconda3/lib/python3.7/site-packages/pipenv'`

Python location: `'/Users/ghalyahalansari/anaconda3/bin/python'`

Python installations found:

  - `3.7.1`: `/Users/ghalyahalansari/anaconda3/bin/python3`
  - `3.7.0`: `/Users/ghalyahalansari/anaconda3/bin/pythonw`
  - `3.7.0`: `/usr/local/bin/python3`
  - `3.7.0`: `/usr/local/bin/python3.7m`
  - `3.5.5`: `//anaconda/bin/python3`
  - `3.5.4`: `//anaconda/bin/pythonw`
  - `2.7.15`: `/usr/local/bin/python`
  - `2.7.15`: `/usr/local/bin/pythonw`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.1',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.2.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST '
                     '2018; root:xnu-4903.241.1~1/RELEASE_X86_64',
 'python_full_version': '3.7.1',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_SESSION_ID`
  - `SSH_AUTH_SOCK`
  - `Apple_PubSub_Socket_Render`
  - `COLORFGBG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `LANG`
  - `PWD`
  - `SHELL`
  - `TERM_PROGRAM_VERSION`
  - `TERM_PROGRAM`
  - `PATH`
  - `COLORTERM`
  - `TERM`
  - `HOME`
  - `TMPDIR`
  - `USER`
  - `XPC_SERVICE_NAME`
  - `LOGNAME`
  - `__CF_USER_TEXT_ENCODING`
  - `ITERM_SESSION_ID`
  - `SHLVL`
  - `OLDPWD`
  - `ZSH`
  - `PAGER`
  - `LESS`
  - `LSCOLORS`
  - `LC_CTYPE`
  - `CONDA_SHLVL`
  - `CONDA_DEFAULT_ENV`
  - `CONDA_EXE`
  - `CONDA_PREFIX`
  - `CONDA_PROMPT_MODIFIER`
  - `CONDA_PYTHON_EXE`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/ghalyahalansari/anaconda3/bin:/anaconda3/bin://anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/ghalyahalansari/Development/env11/task_11`

---------------------------

Contents of `Pipfile` ('/Users/ghalyahalansari/Development/env11/task_11/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
certifi = "==2018.4.16"
chardet = "==3.0.4"
defusedxml = "==0.5.0"
django-allauth = "==0.36.0"
django-crispy-forms = "==1.7.2"
idna = "==2.7"
oauthlib = "==2.1.0"
python3-openid = "==3.1.0"
pytz = "==2018.3"
requests = "==2.19.1"
requests-oauthlib = "==1.0.0"
urllib3 = "==1.23"
Django = "==2.0.4"
Pillow = "==6.0.0"
requirements-txt = "*"

[requires]
python_version = "3.7"

```

</details>
