### ISSUE TITLE
how to pipenv install/upgrade devlop (--dev) packages WITHOUT touching default (app) packages?

### ISSUE THREAD

**Issue by mcallaghan-bsm** [pypa/pipenv#3981]
Hi all, 

Based on https://pipenv.readthedocs.io/en/latest/cli/#pipenv, I am struggling to understand how one is supposed to run python tests (and other fun CI stuff), without also upgrading the base default packages.

So consider:
* we have a Docker image with snapped pipenv to the right base packages via `Pipfile.lock`
* developers and pipelines need to run "pipenv install --dev" in order to get pytest/etc.

Our Requirements:
* we want default (app) packages in `Pipfile` and `Pipfile.lock`
* we want develop (--dev) packages in `Pipfile` but NOT `Pipfile.lock`
* when the app runs, it should ONLY have the app/default packages
* when dev/ci runs, it should have the LATEST version of packages available in `[develop]` from `Pipfile`

The problem:
* "pipenv install --dev" _ALSO_ upgrades the default packages :( -- we DO NOT want to change the base application (default) packages, and ONLY install/upgrade the latest develop packages as needed / on demand;
>  -d, --dev     Install both develop and default packages.

The other options I have considered:

These two are contradictory ...
* `--skip-lock` is good for the "--dev" packages (it is faster, and we don't want to lock dev packages), however then this ALSO upgrades app default packages :(
* `--ignore-pipfile` is good for the default packages (it forces pipenv to use the Pipfile.lock), BUT, we don't want to lock the dev packages!

I see:
* `--selective-upgrade`, and do it ONLY for the dev packages ... but that feels annoying and counter-productive to `--dev`'s purpose!
* `--keep-outdated` not entirely sure if this helps, but I don't think so

Advise? Am I missing it?
Hoping there is some clean command/workflow here to achieve our goals.  I imagine that this is a _common_ set of requirements for projects.

---
+ pipenv --support
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/bin/python'`

Python installations found:

  - `3.7.3`: `/usr/local/bin/python`
  - `3.7.3`: `/usr/local/bin/python3.7m`
  - `3.5.3`: `/usr/bin/python3.5m`
  - `3.5.3`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-64-generic',
 'platform_system': 'Linux',
 'platform_version': '#73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019',
 'python_full_version': '3.7.3',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `HOSTNAME`
  - `PYTHON_PIP_VERSION`
  - `HOME`
  - `GPG_KEY`
  - `TERM`
  - `PATH`
  - `LANG`
  - `PYTHON_VERSION`
  - `PWD`
  - `PYTHONPATH`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/app`

---------------------------

Contents of `Pipfile` ('/app/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
"boto3" = "*"
(SNIP)
mysql-connector-python = "*"
pyodbc = "*"
requests = "*"
xlrd = "*"

[dev-packages]
freezegun = "*"
metrics = "*"
moto = "*"
pyfakefs = "*"
pylint = "*"
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"
pytest-sugar = "*"
pytz = "*"
sqlparse = "*"

[requires]
python_version = "3.7"

```

(SNIP) (lock file N/A for now - it depends/varies when the user runs `lock` ;o)
