### ISSUE TITLE
--bare switch should turn off progress indicator

### ISSUE THREAD

**Issue by dynobo** [pypa/pipenv#4052]
## Issue description

Despite executing pipenv with the `--bare` switch for minimum output, the progress indicator/animation get's shown. This can spam log files. 

In my case the log of Github Actions (used for CI) get's spammed.

### Expected result

`--bare` switch should disable the progress indicator while installing things, just showing like:
 
```
[...]
Creating virtual environment...
Successfully created virtual environment!
[...]
Locking...
Success!
[...]
```
### Actual result

For every change in the progress indicator, a new log-line get's created:

```
$ pipenv --bare install --dev
Creating a virtualenv for this project…
Pipfile: /home/runner/work/normcap/normcap/Pipfile
Using /opt/hostedtoolcache/Python/3.7.5/x64/bin/python3.7 (3.7.5) to create virtualenv…

⠋ Creating virtual environment...
⠙ Creating virtual environment...
⠹ Creating virtual environment...
⠸ Creating virtual environment...
⠼ Creating virtual environment...
⠴ Creating virtual environment...
⠦ Creating virtual environment...

[...  ~100 more lines !!! ...]

⠧ Creating virtual environment...
⠇ Creating virtual environment...
⠇ Creating virtual environment...Already using interpreter /opt/hostedtoolcache/Python/3.7.5/x64/bin/python3.7
Using base prefix '/opt/hostedtoolcache/Python/3.7.5/x64'
New python executable in /home/runner/.local/share/virtualenvs/normcap-titTOeb0/bin/python3.7
Also creating executable in /home/runner/.local/share/virtualenvs/normcap-titTOeb0/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /opt/hostedtoolcache/Python/3.7.5/x64/bin/python3.7

✔ Successfully created virtual environment! 
Virtualenv location: /home/runner/.local/share/virtualenvs/normcap-titTOeb0
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…

⠋ Locking...
⠙ Locking...
⠹ Locking...
⠸ Locking...
⠼ Locking...

[...  ~100 more lines !!! ...]

⠹ Locking...
⠸ Locking...✔ Success! 
Locking [packages] dependencies…

⠋ Locking...
⠙ Locking...
⠹ Locking...
⠸ Locking...
⠼ Locking...

[...  ~100 more lines !!! ...]

⠹ Locking...
⠸ Locking...✔ Success! 
Updated Pipfile.lock (d1ae73)!
Installing dependencies from Pipfile.lock (d1ae73)…
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```

### Steps to replicate

1.) Setup a github action for a repo containing a Pipfile, e.g. like:
```
name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7           
    - name: Install pipenv
      run: |
        pip3 install pipenv
    - name: Install python dependencies
      run: | 
        pipenv --bare install --dev
```

2.) Check output logs of executed action.
