### ISSUE TITLE
Let user choose location of .venv

### ISSUE THREAD

**Issue by woky** [pypa/pipenv#4213]
It's irritating that you cannot specify custom virtual environment directory location. It makes pipenv unsuitable for production deployments. `PIPENV_VENV_IN_PROJECT` is suitable only for development environments.

Consider this scenario using [docker-compose.yaml](https://github.com/docker/compose/) to set up a Docker container:

```
...

  install:
    image: python:3.8
    environment:
      PIPENV_VENV_IN_PROJECT: 1
    volumes:
      - /srv/deploy/app:/app:ro # Note that this is bind mounted read-only
      - /var/cache/libgen-tools-venv:/app/.venv
    # Pipenv writes by default so we pass --keep-outdated
    # because Pipfile.lock is on read-only filesystem.
    command: pipenv sync --keep-outdated

  periodic-batch-job-1:
    image: python:3.8
    environment:
      PIPENV_VENV_IN_PROJECT: 1
    volumes:
      - /srv/deploy/app:/app:ro # Note that this is bind mounted read-only
      - /var/cache/libgen-tools-venv:/app/.venv:ro
    command: pipenv run python3 /app/dostuff.py

  ...
```

Here the project is deployed out of Git/CI/CD into `/srv/deploy/app` and is mounted read-only to containers at `/app`, because more containers share the same code and they have no business overwriting it. But this means that `/app/.venv` cannot be created in containers.

This is very specific example I'm now just dealing with, but having virtual environment in `/var/cache` or any other _volatile_ directory seems to be perfectly legal usage.

I've experimented with exporting `VIRTUAL_ENV` prior to running `pipenv install` but it is ignored.

This issue was previously closed here https://github.com/pypa/pipenv/issues/746.
