### ISSUE TITLE
Peer dependencies of git package not downloaded

### ISSUE THREAD

**Issue by yoshivda** [pypa/pipenv#4291]
### Issue description

Dependencies from a dependency from a git source are no longer automatically installed after the 2020 update.

### Expected result

Install all required packages, including the requirements of dependencies

### Actual result

Peer dependencies are not resolved

### Steps to replicate

Pipfile:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
pycodestyle = {git = "https://github.com/PyCQA/pycodestyle.git"}
generator_python = {git = "https://gitlab.ewi.tudelft.nl/weblab/generator-python.git"}
mock = "*"

[requires]
python_version = "3.8"

[scripts]
all = "sh -c 'pipenv run codestyle && pipenv run generator && pipenv run tests'"
codestyle = "pycodestyle --exclude output,.venv ."
generator = "sh -c 'python -m generator assignments'"
tests = "sh run-tests.sh"
```

After `pipenv install`, running `pipenv run generator` will result in errors due to missing packages. These packages are listed in this repo's setup.py, but are not installed. With `pipenv==2018.11.26` these packages are downloaded and everything works.

**Comment by frostming** [comment]
Can't reproduce here, can you try to minimize the case?
At least `pipenv install git+https://github.com/pallets/flask.git#egg=flask` works fine.

Also can you provide the output of `env|grep -i PIPENV`?

**Comment by yoshivda** [comment]
The case for me: the dependency generator_python requires some packages, these are not installed. The minimal pipfile would just contain that one, and to test it the `generator` script.

The command you list gives no output for me 😕

**Comment by yoshivda** [comment]
An open source repo using the same dependency is [this one](https://gitlab.ewi.tudelft.nl/ads-maths/course-material), see [this job log](https://gitlab.ewi.tudelft.nl/ads-maths/course-material/-/jobs/1313643) to see the failure. This job is a manual rerun, so there were no changes since the last build (which passed)

**Comment by frostming** [comment]
@yoshivda The Pipfile.lock lacks peer dependencies, can you try `pipenv lock --clear` and see whether the file is fixed?

**Comment by techalchemy** [comment]
sorry for asking the dumb question here, but why invoke `python` via `sh`? Does this work if you just change your Pipfile to say:

```toml
[scripts]
all = "pipenv run codestyle && pipenv run generator && pipenv run tests"
codestyle = "pycodestyle --exclude output,.venv ."
generator = "python -m generator implementation --output output/implementation"
generatoranalysis = "python -m non_programming_generator analysis/exercises"
tests = "sh run-tests.sh"
```

You also may want to consider using the full path to `sh`, e.g. `/usr/bin/sh`
