### ISSUE TITLE
Install a package with its version instead of *

### ISSUE THREAD

**Issue by ghost** [pypa/pipenv#4366]
When I install a package, say, flake8 with `pipenv install flake8 -d`/`--dev`, it adds this to the pipfile:
```toml
[dev-packages]
flake8 = *
```
How can I install it to do something like this?
`pipenv install ~flake8 -d `
And I expect it to put this in the pipfile:
```toml
[dev-packages]
flake8 = "~=3.8.3"
```
Right now what I do is before installing a package, I go over to https://pypi.org/project/flake8 and check the version and type `pipenv install flake8~=3.8.3` in the terminal
