### ISSUE TITLE
Allow configuring pipenv though a config file

### ISSUE THREAD

**Issue by ericriff** [pypa/pipenv#4467]
Pipenv supports a lot of configurations though environmental variables. This is useful but those are not persistent and can't be pushed to a VCS.
For example if we have a team of devs working on the same repo, I would like to commit a config file that Pipenv would pick up so all the devs have Pipenv configured the same way.

Thanks!

**Comment by Mause** [comment]
Have you tried adding them to a `.env` file?

**Comment by ericriff** [comment]
> Have you tried adding them to a `.env` file?

https://github.com/pypa/pipenv/issues/2197#issuecomment-445754721

**Comment by matteius** [comment]
I've tried adding a .env file with `PIPENV_VENV_IN_PROJECT=1` and it does not get used when creating the virtualenv on the master branch.   Perhaps we can move the dotenv loading earlier in the process.

**Comment by epomatti** [comment]
@matteius not sure about a .env, although anticipating dotenv loading would make sense on it's own.

It would be good to have a dedicated persistent config spec. One idea below - inspired on another package manager - but could be added  (ideally) directly to the Pipfile.

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[virtualenvs]
in-project = true       # default would be false
directory = ".venv"   # default would be .venv as well

[packages]
pymongo = "*"
flask = "*"

# ...
```

My use case would be based such as in this `.vscode/settings.json`. I just want to clone and do a `pipenv install` without worrying about setting variables. It's right there with the code.

```json
{
  "python.linting.pylintEnabled": true,
  "python.linting.pylintPath": ".venv/bin/pylint",
  "python.formatting.autopep8Path": ".venv/bin/autopep8"
}
```
