### ISSUE TITLE
pipenv check fails on pip

### ISSUE THREAD

**Issue by tucked** [pypa/pipenv#4600]
`pipenv check` can fail on `pip`:
> 38765: pip <19.2 resolved (18.1 installed)!
The pip package before 19.2 for Python allows Directory Traversal when a URL is given in an install command, because a Content-Disposition header can have ../ in a filename, as demonstrated by overwriting the /root/.ssh/authorized_keys file. This occurs in _download_http_url in _internal/download.py.

1. `pip` is not in `Pipfile`(`.lock`).
2. `pip` does not show up in `pipenv graph`.

### Expected result

I expect `pipenv graph` to fully describe the deps in the virtualenv (optionally, using a flag like `--all` as `pipdeptree` and `pip freeze` do).

Perhaps "unavoidable" deps like `pip`, `setuptools`, etc. should be added to `[requires]` on Pipfile generation (as `python_version` is)?

### Actual result

I did not (explicitly) install `pip`, yet `pipenv check` fails on it (good). Further investigation requires directly querying the virtualenv:
``` sh
"$(pipenv --venv)/bin/python" -m pip freeze --all
```

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

``` toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
pip = {version = "<19.2"}

[dev-packages]

[requires]
python_version = "3.6"
```
- Note: This isn't necessary on old OSes where the system `pip` is `<19.2`.
``` sh
pipenv install
pipenv check  # fails
pipenv graph  # empty
```
