### ISSUE TITLE
Normalize package names in Pipfile

### ISSUE THREAD

**Issue by fridex** [pypa/pipenv#4699]
### Issue description

From a consistency point of view, it would be great if Pipenv normalizes package names stored in Pipfile - especially when computing hash on Pipfile.

When running Pipenv with the following Pipfile:

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
Sphinx = "*"
```

Pipenv produces a Pipfile.lock which holds the following hash of Pipfile: `c99365b83495db0f676ba97f11db58b35955f8f5e7da5b56495dbf7044d303bf`

When the package name is normalized:

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
sphinx = "*"
```

Pipenv produces Pipfile.lock with Pipfile hash `d993d725f2bfe31e06c4a1f3716caf2d4b1a9a5d8cb8d24a140b58eabe90a3e3`.

As semantically, Pipfile hasn't changed, it would be great if Pipenv would be consistent in these cases.

### Expected result

Pipfile hash is unified. Ideally, Pipfile should hold [normalized names](https://www.python.org/dev/peps/pep-0503/#normalized-names).

### Steps to replicate

```console
cat << EOF > Pipfile
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
Sphinx = "*"
EOF
```

```console
pipenv install
```

```console
cat Pipfile.lock | jq "._meta.hash"
# {
#   "sha256": "c99365b83495db0f676ba97f11db58b35955f8f5e7da5b56495dbf7044d303bf"
# }
```

```console
cat << EOF > Pipfile
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
sphinx = "*"
EOF
```

```console
pipenv install
```

```console
cat Pipfile.lock | jq "._meta.hash"
# {
#   "sha256": "d993d725f2bfe31e06c4a1f3716caf2d4b1a9a5d8cb8d24a140b58eabe90a3e3"
# }
```

```console
pipenv --version
# pipenv, version 2020.11.15
````
