### ISSUE TITLE
Install of matplotlib failing

### ISSUE THREAD

**Issue by Robinbloke** [pypa/pipenv#4984]
Python 3.8.0
Pipenv 2022.1.8
matplotlib
Raspberry Pi, running raspbian stretch lite

### Issue description

I have successfully installed most of the modules I want to use and have a working Pipfile for them.
But matplotlib fails and fails when I try to install it.

### Expected result

The install to work!

### Actual result

Install failed with error, see matplotlib-installfail.txt

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

Install Pipfile and then try to install matplotlib

Pipfile attached
-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2022.1.8'`

Pipenv location: `'/usr/lib/python3.8/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.8.0`: `/usr/bin/python3.8`
  - `3.8.0`: `/usr/bin/python3`
  - `3.5.3`: `/usr/bin/python3.5m`
  - `3.5.3`: `/usr/bin/python3.5`
  - `2.7.13`: `/usr/bin/python`
  - `2.7.13`: `/usr/bin/python2`
  - `2.7.13`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.0',
 'os_name': 'posix',
 'platform_machine': 'armv7l',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.19.66-v7+',
 'platform_system': 'Linux',
 'platform_version': '#1253 SMP Thu Aug 15 11:49:46 BST 2019',
 'python_full_version': '3.8.0',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LS_COLORS`
  - `SSH_CONNECTION`
  - `LANG`
  - `XDG_SESSION_ID`
  - `USER`
  - `PWD`
  - `HOME`
  - `TEXTDOMAIN`
  - `SSH_CLIENT`
  - `SSH_TTY`
  - `MAIL`
  - `TERM`
  - `SHELL`
  - `SHLVL`
  - `PYTHONPATH`
  - `LOGNAME`
  - `XDG_RUNTIME_DIR`
  - `PATH`
  - `OLDPWD`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/pit/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/home/pit/workspace/PIT/pit`

---------------------------

Contents of `Pipfile` ('/home/pit/workspace/PIT/pit/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
scp = "==0.13.2"
paramiko = "==2.7.1"
atomicwrites = "==1.3.0"
attrs = "==20.3.0"
certifi = "==2019.6.16"
chardet = "==3.0.4"
idna = "==2.8"
importlib-metadata = "==0.19"
more-itertools = "==7.2.0"
pathlib2 = "==2.3.4"
pluggy = "==0.13.1"
ply = "==3.11"
py = "==1.10.0"
pyparsing = "==2.4.7"
pyserial = "==3.5"
logilab-common = "==1.8.0"
pytest = "==6.2.1"
pytz = "==2019.2"
requests = "==2.22.0"
six = "==1.15.0"
smbus = "==1.1.post2"
tftpy = "==0.8.0"
urllib3 = "==1.25.3"
wcwidth = "==0.1.7"
zipp = "==0.5.2"
numpy = "*"
pytest-ordering = "==0.6"
pytest-reportlog = "==0.1.2"
pyasn1 = "==0.4.8"
pysmi = "==0.3.4"
pycryptodomex = "==3.9.9"
pysnmp = "==4.4.12"
"RPi.GPIO" = "==0.7.0"
pycec = "*"

[dev-packages]

[requires]
python_version = "3.8"

```

</details>

[Pipfile.txt](https://github.com/pypa/pipenv/files/8246670/Pipfile.txt)

[matplotlib-installfail.txt](https://github.com/pypa/pipenv/files/8246664/matplotlib-installfail.txt)
[pipenv-support.txt](https://github.com/pypa/pipenv/files/8246666/pipenv-support.txt)
