### ISSUE TITLE
Custom scripts shortcut with --system option

### ISSUE THREAD

**Issue by webartoli** [pypa/pipenv#5115]
### The problem

I use quite often pipenv and Docker container. In docker container I want to avoid virtualenv so my install script is:

```bash
> pipenv install --system --deploy
```

I'm always frustrated when i need to retype commands on both `Pipfile` and `ci-config.yml`

```ini
[scripts]
test = pytest --option1=foo --option2=bar
```

```yml
test:
  before_script:
    - pipenv install --system --deploy
  script: 
    - pytest --option1=foo --option2=bar # cannot use pipenv here
```

### Describe the solution you'd like

I would like to specify my custom command with its own option once and call it via Pipenv

```yml
test:
  before_script:
    - pipenv install --system --deploy
  script: 
    - pipenv run --system test # or pipenv --system run test
```
