### ISSUE TITLE
Relative file path in Pipfile being converted to Absolute file path in Pipfile.lock

### ISSUE THREAD

**Issue by bendog** [pypa/pipenv#5489]
### Issue description

Using the file install method for Pipenv, we've run into an issue with a relative path being converted to an absolute path on locking. This prevents us from using the lock file to install from as the path will very from user to user.

I've tried changing the method of import, and I've tried removing the .lock file, but it still gets built at an absolute path. 

pipenv, version 2022.9.24

Pipfile
```
himl = {file = "./lib/himl"}
```

### Expected result

Expected result would be a portable lock file that references the location relatively

Pipfile.lock
```
        "himl": {
            "file": "./lib/himl",
            "version": "==0.5.4"
        },
```

### Actual result

Pipfile.lock
```
        "himl": {
            "file": "file:///Users/username/dev/livemine-hole-information-service/hole-information-loader/lib/himl",
            "version": "==0.5.4"
        },
```

### Steps to replicate

Given a Pipfile containing a relative file import.
When the user runs `pipenv lock`
Then the Pipfile.lock file generated converts the relative file location for an absolute file location for the machine it was run on.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2022.9.24'`

Pipenv location: `'/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv'`

Python location: `'/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/bin/python3.10'`

OS Name: `'posix'`

User pip version: `'22.2.2'`

user Python installations found:

  - `3.10.8`: `/opt/homebrew/bin/python3`
  - `3.10.5`: `~/.pyenv/versions/3.10.5/bin/python3`
  - `3.10.1`: `~/.pyenv/versions/3.10.1/bin/python3`
  - `3.9.15`: `/opt/homebrew/bin/python3.9`
  - `3.9.13`: `~/.pyenv/versions/3.9.13/bin/python3`
  - `3.9.6`: `/usr/bin/python3`
  - `3.8.15`: `/opt/homebrew/bin/python3.8`
  - `3.7.12`: `~/.local/share/virtualenvs/hole-information-loader-UUj0tf3n/bin/python3`
  - `3.7.12`: `~/.local/share/virtualenvs/hole-information-loader-UUj0tf3n/bin/python`
  - `3.7.12`: `~/.local/share/virtualenvs/hole-information-loader-UUj0tf3n/bin/python3.7m`
  - `3.7.12`: `~/.local/share/virtualenvs/hole-information-loader-UUj0tf3n/bin/python3.7`
  - `3.7.12`: `~/.local/share/virtualenvs/hole-information-loader-UUj0tf3n/bin/python3`
  - `3.7.12`: `~/.local/share/virtualenvs/hole-information-loader-UUj0tf3n/bin/python`
  - `3.7.12`: `~/.local/share/virtualenvs/hole-information-loader-UUj0tf3n/bin/python3.7m`
  - `3.7.12`: `~/.local/share/virtualenvs/hole-information-loader-UUj0tf3n/bin/python3.7`
  - `3.7.12`: `~/.pyenv/versions/3.7.12/bin/python3`
  - `3.6.15`: `~/.pyenv/versions/3.6.15/bin/python3`
  - `2.7.18`: `~/.pyenv/versions/2.7.18/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.8',
 'os_name': 'posix',
 'platform_machine': 'arm64',
 'platform_python_implementation': 'CPython',
 'platform_release': '21.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT '
                     '2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000',
 'python_full_version': '3.10.8',
 'python_version': '3.10',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `MANPATH`
  - `LDFLAGS`
  - `TERM_PROGRAM`
  - `PYENV_ROOT`
  - `_P9K_TTY`
  - `PIP_PYTHON_PATH`
  - `TERM`
  - `SHELL`
  - `TMPDIR`
  - `HOMEBREW_REPOSITORY`
  - `CPPFLAGS`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `ZSH`
  - `USER`
  - `pipfile_dir`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `VIRTUAL_ENV`
  - `PAGER`
  - `LSCOLORS`
  - `PIPENV_ACTIVE`
  - `_`
  - `__CFBundleIdentifier`
  - `PWD`
  - `P9K_SSH`
  - `LANG`
  - `P9K_TTY`
  - `XPC_FLAGS`
  - `PYTHONDONTWRITEBYTECODE`
  - `XPC_SERVICE_NAME`
  - `HOME`
  - `SHLVL`
  - `PYENV_SHELL`
  - `HOMEBREW_PREFIX`
  - `LOGNAME`
  - `LESS`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PKG_CONFIG_PATH`
  - `HOMEBREW_CELLAR`
  - `INFOPATH`
  - `GDAL_CONFIG`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/tools:/Users/fitzbe/.local/bin:/Users/fitzbe/.pyenv/shims:/Users/fitzbe/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/fitzbe/.local/share/virtualenvs/hole-information-loader-UUj0tf3n/bin:/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/tools:/Users/fitzbe/.local/bin:/Users/fitzbe/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/fitzbe/Library/Application Support/JetBrains/Toolbox/scripts:/Users/fitzbe/Library/Application Support/JetBrains/Toolbox/scripts`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_AU.UTF-8`
  - `PWD`: `livemine-hole-information-service/hole-information-loader`
  - `VIRTUAL_ENV`: `~/.local/share/virtualenvs/hole-information-loader-UUj0tf3n`

---------------------------

Contents of `Pipfile` (livemine-hole-information-service/hole-information-loader/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
arrow = "~=0.14.4"
bc = "==0.0.1"
boto3 = "==1.9.202"
numpy = "==1.21.6" # PINNED for speed
pandas = "==1.3.5"  #updated
pyproj = "==2.5.0" # REQUIRES https://proj.org/
pyyaml = "==5.1.2"
cx-oracle = "==7.2.2"
kafka-python = "==2.0.1"
pymssql = "==2.1.4" # REQUIRES freetds
pymongo = "==3.9.0"
himl = {file = "./lib/himl"}

[dev-packages]
coverage = "==4.5.4"
isort = "*"
fakeredis = "==1.1.0"
mongomock = "==3.19.0"
requests-mock = "==1.7.0"
pylint = "==2.4.4"

[requires]
python_version = "3.7"

```

</details>
