### ISSUE TITLE
Stuck on resolving dependencies during installation

### ISSUE THREAD

**Issue by niturk** [pypa/pipenv#5505]
### Pipfile

[dev-packages]
black = "*"
isort = "*"
flake8 = "*"
#flake8-bugbear = "*"
#flake8-comprehensions = "*"
flake8-builtins = "*"
#flake8-bandit = "*"
flake8-eradicate = "*"
flake8-print = "*"
pep8-naming = "*"
vulture = "*"

### Issue description

#flake8-bugbear = "*"
#flake8-comprehensions = "*"
#flake8-bandit = "*"

When I close these three of the dev packages, pipenv installs without any problem. But if I uncomment even one of them, it waits forever in the resolving depencensies step for dev packages.

$ pipenv install --dev

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2022.11.25'`

Pipenv location: `'***********.local/lib/python3.10/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

OS Name: `'posix'`

User pip version: `'22.3'`

user Python installations found:

  - `3.10.7`: `/usr/bin/python3`
  - `3.10.7`: `/bin/python3`
  - `3.9.15`: `/usr/bin/python3.9`
  - `3.9.15`: `/bin/python3.9`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.7',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '6.0.7-060007-generic',
 'platform_system': 'Linux',
 'platform_version': '#202211031652 SMP PREEMPT_DYNAMIC Thu Nov 3 18:33:21 UTC '
                     '2022',
 'python_full_version': '3.10.7',
 'python_version': '3.10',
 'sys_platform': 'linux'}
```

System environment variables:

  - `USER`
  - `LC_TIME`
  - `XDG_SESSION_TYPE`
  - `SHLVL`
  - `HOME`
  - `OLDPWD`
  - `LESS`
  - `DESKTOP_SESSION`
  - `ZSH`
  - `LSCOLORS`
  - `GTK_MODULES`
  - `GNOME_SHELL_SESSION_MODE`
  - `PAGER`
  - `PS1`
  - `LC_MONETARY`
  - `SYSTEMD_EXEC_PID`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `COLORTERM`
  - `DEBUGINFOD_URLS`
  - `GNOME_KEYRING_CONTROL`
  - `MANDATORY_PATH`
  - `LOGNAME`
  - `PYTHONDONTWRITEBYTECODE`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `DEFAULTS_PATH`
  - `XDG_SESSION_CLASS`
  - `USERNAME`
  - `TERM`
  - `GNOME_DESKTOP_SESSION_ID`
  - `WINDOWPATH`
  - `PATH`
  - `SESSION_MANAGER`
  - `GNOME_TERMINAL_SCREEN`
  - `XDG_MENU_PREFIX`
  - `XDG_RUNTIME_DIR`
  - `LC_ADDRESS`
  - `DISPLAY`
  - `PIPENV_ACTIVE`
  - `LANG`
  - `XDG_CURRENT_DESKTOP`
  - `LC_TELEPHONE`
  - `XMODIFIERS`
  - `XDG_SESSION_DESKTOP`
  - `GNOME_TERMINAL_SERVICE`
  - `XAUTHORITY`
  - `LS_COLORS`
  - `SSH_AUTH_SOCK`
  - `SSH_AGENT_LAUNCHER`
  - `SHELL`
  - `LC_NAME`
  - `QT_ACCESSIBILITY`
  - `GDMSESSION`
  - `GEM_HOME`
  - `PIP_PYTHON_PATH`
  - `LC_MEASUREMENT`
  - `LC_IDENTIFICATION`
  - `GPG_AGENT_INFO`
  - `QT_IM_MODULE`
  - `PWD`
  - `XDG_CONFIG_DIRS`
  - `XDG_DATA_DIRS`
  - `LC_NUMERIC`
  - `LC_PAPER`
  - `VTE_VERSION`
  - `CHROME_DESKTOP`
  - `ORIGINAL_XDG_CURRENT_DESKTOP`
  - `GDK_BACKEND`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `GIT_ASKPASS`
  - `VSCODE_GIT_ASKPASS_NODE`
  - `VSCODE_GIT_ASKPASS_EXTRA_ARGS`
  - `VSCODE_GIT_ASKPASS_MAIN`
  - `VSCODE_GIT_IPC_HANDLE`
  - `VSCODE_INJECTION`
  - `ZDOTDIR`
  - `USER_ZDOTDIR`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

---------------------------

Contents of `Pipfile` ('*******/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
peewee = "~=3.15.0"
pysqlcipher3 = "~=1.1.0"
requests = "~=2.28.0"
requests-oauthlib = "~=1.3.0"
pycryptodome = "~=3.15.0"
numpy = "~=1.23.0"
sentry-sdk = "~=1.11.0"
opencv-python-headless = "~=4.6.0"
flask = "~=2.2.0"

[dev-packages]
black = "*"
isort = "*"
flake8 = "*"
flake8-bugbear = "*"
flake8-comprehensions = "*"
flake8-builtins = "*"
flake8-bandit = "*"
flake8-eradicate = "*"
flake8-print = "*"
pep8-naming = "*"
vulture = "*"

[requires]
python_version = "3.9"

[pipenv]
allow_prereleases = true
```

</details>
