### ISSUE TITLE
How to debug lock failure?

### ISSUE THREAD

**Issue by powlo** [pypa/pipenv#5596]
How can I debug this lock failure?

> paul.backhouse@HOLBMAC2365 sc-sss-python % pipenv lock       
> Loading .env environment variables...
> Locking [packages] dependencies...
> Building requirements...
> Resolving dependencies...
> ✘ Locking Failed! 
> 
> psycopg2~=2.9 ; sys_platform == 'linux' doesn't match your environment, its dependencies won't be resolved.
> CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Cannot install -r /var/folders/dr/2c16nvsn0bz62n72t9jyzc8sq09h4t/T/pipenv5fjudwv9requirements/pipenv-4ljc3f3p-constraints.txt (line 5) and click~=8.1 because these package versions have conflicting dependencies.
> [ResolutionFailure]:   File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 782, in _main
> [ResolutionFailure]:       resolve_packages(
> [ResolutionFailure]:   File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 730, in resolve_packages
> [ResolutionFailure]:       results, resolver = resolve(
> [ResolutionFailure]:   File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 709, in resolve
> [ResolutionFailure]:       return resolve_deps(
> [ResolutionFailure]:   File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 1119, in resolve_deps
> [ResolutionFailure]:       results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
> [ResolutionFailure]:   File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 908, in actually_resolve_deps
> [ResolutionFailure]:       resolver.resolve()
> [ResolutionFailure]:   File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 695, in resolve
> [ResolutionFailure]:       raise ResolutionFailure(message=str(e))
> [pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
>   You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
>   Hint: try $ pipenv lock --pre if it is a pre-release dependency.
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

The referenced file (pipenv-4ljc3f3p-constraints.txt) disappears after the failure (assuming it existed in the first place). Following the instructions doesn't reveal a conflicted version. In this case requirements for click seem to be met:

> paul.backhouse@HOLBMAC2365 sc-sss-python % pipenv install --skip-lock  
> Loading .env environment variables...
> Installing dependencies from Pipfile...
> To activate this project's virtualenv, run pipenv shell.
> Alternatively, run a command inside the virtualenv with pipenv run.
> 
> paul.backhouse@HOLBMAC2365 sc-sss-python % pipenv graph | grep "click"
> Loading .env environment variables...
>   - click [required: >=8.0.0, installed: 8.1.3]
>   - click [required: >=7.1.2,<9, installed: 8.1.3]
>   - click-log [required: ==0.3.2, installed: 0.3.2]
>     - click [required: Any, installed: 8.1.3]
>     - click [required: ==8.1.3, installed: 8.1.3]
>     - click [required: ==8.1.3, installed: 8.1.3]
>     - click [required: ==8.1.3, installed: 8.1.3]

NB The package that is flagged as in conflict varies from run to run.

I can't figure out what pipenv is trying to tell me. Maybe a bug?

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2023.2.4'`

Pipenv location: `'/opt/homebrew/Cellar/pipenv/2023.2.4/libexec/lib/python3.11/site-packages/pipenv'`

Python location: `'/opt/homebrew/Cellar/pipenv/2023.2.4/libexec/bin/python3.11'`

OS Name: `'posix'`

User pip version: `'22.3.1'`

user Python installations found:

  - `3.10.9`: `/opt/homebrew/bin/python3`
  - `3.9.11`: `/Library/Frameworks/Python.framework/Versions/3.9/bin/python3`
  - `3.9.11`: `/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9`
  - `3.9.11`: `/usr/local/bin/python3`
  - `3.9.11`: `/usr/local/bin/python3.9`
  - `3.9.6`: `/usr/bin/python3`
  - `3.8.16`: `/opt/homebrew/bin/python3.8`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.11.1',
 'os_name': 'posix',
 'platform_machine': 'arm64',
 'platform_python_implementation': 'CPython',
 'platform_release': '21.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:46 PDT '
                     '2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T8101',
 'python_full_version': '3.11.1',
 'python_version': '3.11',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `TERM_PROGRAM`
  - `TERM`
  - `SHELL`
  - `PIPENV_VENV_IN_PROJECT`
  - `TMPDIR`
  - `DIRENV_DIR`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `DIRENV_WATCHES`
  - `_`
  - `LaunchInstanceID`
  - `__CFBundleIdentifier`
  - `PWD`
  - `JAVA_HOME`
  - `LANG`
  - `XPC_FLAGS`
  - `DL_PRODUCT_TOPIC`
  - `DOCKER_DEFAULT_PLATFORM`
  - `COVERAGE_DIRECTORIES`
  - `SNAPSHOT_METADATA_KAFKA_TOPIC`
  - `DIRENV_FILE`
  - `XPC_SERVICE_NAME`
  - `POETRY_VIRTUALENVS_IN_PROJECT`
  - `HOME`
  - `SHLVL`
  - `LOGNAME`
  - `DIRENV_DIFF`
  - `SECURITYSESSIONID`
  - `__CF_USER_TEXT_ENCODING`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `true`

Debug–specific environment variables:

  - `PATH`: `/opt/homebrew/Cellar/pipenv/2023.2.4/libexec/tools:/Users/paul.backhouse/.npm-global/bin:/Users/paul.backhouse/Library/Python/3.10/bin:/Users/paul.backhouse/.local/bin:/opt/homebrew/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/confluent-7.2.2/bin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/Users/paul.backhouse/workspace/sc-sss-python`

---------------------------

Contents of `Pipfile` ('/Users/paul.backhouse/workspace/sc-sss-python/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[[source]]
name = "internal"
url = "https://aws:${CODEARTIFACT_AUTH_TOKEN}@<internalrepo>/simple"
verify_ssl = true

[dev-packages]
black = "~=22.3"
factory-boy = "~=3.2"
freezegun = "~=1.2"
pebble = "~=5.0"
pytest-asyncio = "~=0.19"
pytest = "~=7.1"
responses = "~=0.20"
pre-commit = "~=2.20"
yappi = "~=1.3"
iss = {editable = true, path = "."}
ipdb = "~=0.13"

[packages]
alembic = "~=1.8"
boto3 = "~=1.22"
click = "~=8.1"
coverage = "~=6.5"
httpx = "~=0.23"
marshmallow = "~=3.15"
marshmallow-sqlalchemy = "~=0.28"
requests = "~=2.28"
sqlalchemy = "~=1.4"
xxhash = "~=3.2"
orjson = "~=3.8"
aws-xray-sdk = "~=2.9"
psycopg2-binary = {version = "~=2.9",sys_platform = "== 'darwin'"}
psycopg2 = {version = "~=2.9", sys_platform = "== 'linux'"}
aiobotocore = "~=2.4"
aiohttp = "~=3.8"
asyncpgsa = "~=0.27"
invoke = "~=1.7"
confluent-kafka = "~=1.9"
botocore = "~=1.27"
python-schema-registry-client = "~=2.4"
fastavro = "~=1.7"
mock-alchemy = "~=0.2"
ecs-deploy = "~=1.13"
cachetools = "~=5.2"
redacted-packages-that-use-internal= { version="*", index="internal" }
redacted-local-package = {path = "path-to-wheel-0.1.0-py3-none-any.whl"}

[requires]
python_version = "3.8"

[pipenv]
allow_prereleases = false

```

</details>
