### ISSUE TITLE
"SyntaxError: invalid syntax" when running pipenv

### ISSUE THREAD

**Issue by lyrixx** [pypa/pipenv#5604]
### Issue description

When in run `pipenv install` in a clean folder, I get and error:

```
  File "/home/gregoire/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 177
    markers = {normalize_marker_str(f"{k} {entry_dict.pop(k)}") for k in keys_in_dict}
                                                             ^
SyntaxError: invalid syntax
```

### Expected result

It should run

### Actual result

```
>/tmp/foobar/rio-pythong pipenv install
Creating a virtualenv for this project...
Pipfile: /tmp/foobar/rio-pythong/Pipfile
Using /usr/bin/python2.7 (2.7.18) to create virtualenv...
⠹ Creating virtual environment...created virtual environment CPython2.7.18.final.0-64 in 163ms
  creator CPython2Posix(dest=/home/gregoire/.local/share/virtualenvs/rio-pythong-SjVsUuss, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/gregoire/.local/share/virtualenv)
    added seed packages: pip==20.3.4, setuptools==44.1.1, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /home/gregoire/.local/share/virtualenvs/rio-pythong-SjVsUuss
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!
⠹ Locking...
  File "/home/gregoire/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 177
    markers = {normalize_marker_str(f"{k} {entry_dict.pop(k)}") for k in keys_in_dict}
                                                             ^
SyntaxError: invalid syntax
```

### Steps to replicate

I put the following file in a new folder, then run `pipenv install`

<details>

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
fabric = ">=1.10.2,<2.0"
docker-compose = ">=1.23.0"
pycodestyle = ">=1.7.0"
"enum34" = "*"
jsonschema = "*"
docker = "*"
requests = ">=2.20"
"backports.ssl-match-hostname" = "*"
"functools32" = "*"
ipaddress = "*"
datadog = "*"
pyyaml = "*" # ">=4.2b1"
prettytable = "*"
mitogen = "*"
ansible-merge-vars = "*"
openstacksdk = "*"
packaging = "*"
ansible-lint = "*"
slackclient = "*"
ansible = ">=2.0,<2.10"
watchdog = ">=0.10,<1.0"
cryptography = ">=2.0,<3.0"

[dev-packages]

[requires]
python_version = "2.7"
# [pipenv]
# allow_prereleases = true
```

</details>

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2023.2.4'`

Pipenv location: `'/home/gregoire/.local/lib/python3.10/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

OS Name: `'posix'`

User pip version: `'22.3.1'`

user Python installations found:

  - `3.10.6`: `/usr/bin/python3`
  - `3.10.6`: `/usr/bin/python`
  - `3.10.6`: `/bin/python3`
  - `3.10.6`: `/bin/python`
  - `2.7.18`: `/usr/bin/python2.7`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/bin/python2.7`
  - `2.7.18`: `/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.6',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.15.0-58-generic',
 'platform_system': 'Linux',
 'platform_version': '#64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023',
 'python_full_version': '3.10.6',
 'python_version': '3.10',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `SESSION_MANAGER`
  - `QT_ACCESSIBILITY`
  - `COLORTERM`
  - `XDG_CONFIG_DIRS`
  - `SSH_AGENT_LAUNCHER`
  - `LESS`
  - `HISTCONTROL`
  - `XDG_MENU_PREFIX`
  - `TERM_PROGRAM_VERSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `TMUX`
  - `HISTSIZE`
  - `LC_ADDRESS`
  - `GNOME_SHELL_SESSION_MODE`
  - `LC_NAME`
  - `SSH_AUTH_SOCK`
  - `GIT_PS1_SHOWDIRTYSTATE`
  - `RIPGREP_CONFIG_PATH`
  - `XMODIFIERS`
  - `DESKTOP_SESSION`
  - `LC_MONETARY`
  - `EDITOR`
  - `GTK_MODULES`
  - `PWD`
  - `XDG_SESSION_DESKTOP`
  - `LOGNAME`
  - `XDG_SESSION_TYPE`
  - `SYSTEMD_EXEC_PID`
  - `BUILDKIT_PROGRESS`
  - `XAUTHORITY`
  - `IM_CONFIG_CHECK_ENV`
  - `CDPATH`
  - `HOME`
  - `USERNAME`
  - `IM_CONFIG_PHASE`
  - `LC_PAPER`
  - `LANG`
  - `LS_COLORS`
  - `XDG_CURRENT_DESKTOP`
  - `FAB_COMPLETION_CACHE_TASKS`
  - `VTE_VERSION`
  - `WAYLAND_DISPLAY`
  - `FASTLY_API_TOKEN`
  - `ANSIBLE_STDOUT_CALLBACK`
  - `GNOME_TERMINAL_SCREEN`
  - `DOCKER_BUILDKIT`
  - `GNOME_SETUP_DISPLAY`
  - `COMPOSE_DOCKER_CLI_BUILD`
  - `XDG_SESSION_CLASS`
  - `TERM`
  - `LC_IDENTIFICATION`
  - `USER`
  - `TMUX_PANE`
  - `GNOME_TERMINAL_SERVICE`
  - `DISPLAY`
  - `SHLVL`
  - `LC_TELEPHONE`
  - `QT_IM_MODULE`
  - `LC_MEASUREMENT`
  - `ARTE_NPM_TOKEN`
  - `XDG_RUNTIME_DIR`
  - `LC_TIME`
  - `FAB_COMPLETION_CACHED_TASKS_FILENAME`
  - `XDG_DATA_DIRS`
  - `PATH`
  - `HISTIGNORE`
  - `GDMSESSION`
  - `HISTFILESIZE`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `GIT_PS1_SHOWUNTRACKEDFILES`
  - `COMPOSER_AUTH_ARTE`
  - `LC_NUMERIC`
  - `OLDPWD`
  - `GOPATH`
  - `TERM_PROGRAM`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/gregoire/.platformsh/bin:./node_modules/.bin:/home/gregoire/.platformsh/bin:./node_modules/.bin:/home/gregoire/.platformsh/bin:/home/gregoire/.cargo/bin:./node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/go/bin:/home/gregoire/.cargo/bin/:/home/gregoire/.local/bin/:/home/gregoire/.yarn/bin/:/home/gregoire/.rvm/bin:/usr/local/go/bin:/home/gregoire/.cargo/bin/:/home/gregoire/.local/bin/:/home/gregoire/.yarn/bin/:/usr/local/go/bin:/home/gregoire/.cargo/bin/:/home/gregoire/.local/bin/:/home/gregoire/.yarn/bin/:/home/gregoire/.rvm/bin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `/usr/bin/vim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/tmp/foobar/rio-pythong`

---------------------------

Contents of `Pipfile` ('/tmp/foobar/rio-pythong/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
fabric = ">=1.10.2,<2.0"
docker-compose = ">=1.23.0"
pycodestyle = ">=1.7.0"
"enum34" = "*"
jsonschema = "*"
docker = "*"
requests = ">=2.20"
"backports.ssl-match-hostname" = "*"
"functools32" = "*"
ipaddress = "*"
datadog = "*"
pyyaml = "*" # ">=4.2b1"
prettytable = "*"
mitogen = "*"
ansible-merge-vars = "*"
openstacksdk = "*"
packaging = "*"
ansible-lint = "*"
slackclient = "*"
ansible = ">=2.0,<2.10"
watchdog = ">=0.10,<1.0"
cryptography = ">=2.0,<3.0"

[dev-packages]

[requires]
python_version = "2.7"
# [pipenv]
# allow_prereleases = true


```

</details>
