### ISSUE TITLE
Ability to specify universal2 wheel packages in a marker

### ISSUE THREAD

**Issue by danrossi** [pypa/pipenv#6356]
I've been trying to get locally merged universal2 wheels working for packages that don't supply them I ran into many bugs getting them installed via pipenv. But have run into another issue where installing `httptools` installs the arm64 version when the universal2 wheel is required.

A marker to specify that would be nice if not documented. 

I have to then download the specific wheel like the others and set it up for installation in Pipenv but found a bug where it won't choose the local wheel and has to be installed manually. 

I tried 

```
pipenv run pip install --implementation py httptools 
```
but failed

It currently looks like this in the Pipfile but should be specific for macos

```
httptools = "*"
```

**Comment by matteius** [comment]
Pipenv already supports `platform_machine` as a marker — both as a shorthand Pipfile key and inside the `markers` field. For example:

```toml
[packages]
# Shorthand form:
httptools = {version = "*", platform_machine = "== 'arm64'"}

# Full markers form:
httptools = {version = "*", markers = "sys_platform == 'darwin' and platform_machine == 'arm64'"}
```

However, it's important to note that PEP 508 markers control **whether** a package is installed (conditional installation), **not which wheel variant** pip selects. There is no marker value for `universal2` — that's a macOS wheel compatibility tag, not a `platform_machine` value. On an Apple Silicon Mac, `platform_machine` evaluates to `'arm64'`.

For installing a specific universal2 wheel, you have a few options:

1. **Local wheel file via `file` or `path`:**
   ```toml
   [packages]
   httptools = {file = "wheels/httptools-0.6.1-cp313-cp313-macosx_11_0_universal2.whl"}
   ```

2. **Pass `--platform` to pip via extra args:**
   ```bash
   PIPENV_EXTRA_PIP_ARGS='["--platform", "macosx_11_0_universal2", "--only-binary", ":all:"]' pipenv install httptools
   ```

This was a documentation gap — PR #6539 adds documentation for the shorthand marker keys and architecture-specific examples.
